// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.viplending.viplending;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetDiscountRateConfigsDataUsdtLevels {
  /** Left end point of gradient interval, left<amount<=right */
  @JsonProperty("left")
  private Long left;

  /** Right end point of gradient interval, left<amount<=right */
  @JsonProperty("right")
  private Long right;

  /** Discount rate */
  @JsonProperty("discountRate")
  private String discountRate;
}
