// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.viplending.viplending;

import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class VipLendingApiImpl implements VipLendingApi {
  private final Transport transport;

  public VipLendingApiImpl(Transport transport) {
    this.transport = transport;
  }

  public GetDiscountRateConfigsResp getDiscountRateConfigs() {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/otc-loan/discount-rate-configs",
        null,
        GetDiscountRateConfigsResp.class,
        false);
  }

  public GetLoanInfoResp getLoanInfo() {
    return this.transport.call(
        "spot", false, "GET", "/api/v1/otc-loan/loan", null, GetLoanInfoResp.class, false);
  }

  public GetAccountsResp getAccounts() {
    return this.transport.call(
        "spot", false, "GET", "/api/v1/otc-loan/accounts", null, GetAccountsResp.class, false);
  }
}
