<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Broker\Ndbroker;

use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Serializer;
use KuCoin\UniversalSDK\Internal\Interfaces\Serializable;

class GetDepositListReq implements Serializable
{
    /**
     * @var string[] $pathVarMapping
     * @Exclude()
     */
    public static $pathVarMapping = [];

    public function pathVarMapping()
    {
        return self::$pathVarMapping;
    }
    /**
     * currency
     * @var string|null $currency
     * @Type("string")
     * @SerializedName("currency")
     */
    public $currency;
    /**
     * Status. Available value: PROCESSING, SUCCESS, FAILURE
     * @var string|null $status
     * @Type("string")
     * @SerializedName("status")
     */
    public $status;
    /**
     * hash
     * @var string|null $hash
     * @Type("string")
     * @SerializedName("hash")
     */
    public $hash;
    /**
     * Start time (milliseconds)
     * @var int|null $startTimestamp
     * @Type("int")
     * @SerializedName("startTimestamp")
     */
    public $startTimestamp;
    /**
     * End time (milliseconds); default sorting in descending order
     * @var int|null $endTimestamp
     * @Type("int")
     * @SerializedName("endTimestamp")
     */
    public $endTimestamp;
    /**
     * Maximum number of returned items, maximum 1000, default 1000
     * @var int|null $limit
     * @Type("int")
     * @SerializedName("limit")
     */
    public $limit = 1000;

    private function __construct() {}

    /**
     * @param Serializer $serializer
     * @return string
     */
    public function jsonSerialize($serializer)
    {
        return $serializer->serialize($this, "json");
    }

    /**
     * @param string $json
     * @param Serializer $serializer
     * @return self
     */
    public static function jsonDeserialize($json, $serializer)
    {
        if ($json == null) {
            return new self();
        }
        return $serializer->deserialize(
            $json,
            GetDepositListReq::class,
            "json"
        );
    }
    /**
     * Creates a new instance of the `GetDepositListReq` class.
     * The builder pattern allows step-by-step construction of a `GetDepositListReq` object.
     * @return GetDepositListReqBuilder
     */
    public static function builder()
    {
        return new GetDepositListReqBuilder(new self());
    }

    /**
     * Creates a new instance of the `GetDepositListReq` class with the given data.
     * Ensure that the keys in data match the target field names in the documentation,
     * rather than the variable names in the class.
     * @return self
     */
    public static function create(array $data)
    {
        $obj = new self();
        foreach ($data as $key => $value) {
            if (property_exists($obj, $key)) {
                $obj->$key = $value;
            }
        }
        return $obj;
    }
}

class GetDepositListReqBuilder
{
    /**
     * @var GetDepositListReq $obj
     */
    private $obj;

    public function __construct(GetDepositListReq $obj)
    {
        $this->obj = $obj;
    }
    /**
     * currency
     * @param string $value
     * @return self
     */
    public function setCurrency($value)
    {
        $this->obj->currency = $value;
        return $this;
    }

    /**
     * Status. Available value: PROCESSING, SUCCESS, FAILURE
     * @param string $value
     * @return self
     */
    public function setStatus($value)
    {
        $this->obj->status = $value;
        return $this;
    }

    /**
     * hash
     * @param string $value
     * @return self
     */
    public function setHash($value)
    {
        $this->obj->hash = $value;
        return $this;
    }

    /**
     * Start time (milliseconds)
     * @param int $value
     * @return self
     */
    public function setStartTimestamp($value)
    {
        $this->obj->startTimestamp = $value;
        return $this;
    }

    /**
     * End time (milliseconds); default sorting in descending order
     * @param int $value
     * @return self
     */
    public function setEndTimestamp($value)
    {
        $this->obj->endTimestamp = $value;
        return $this;
    }

    /**
     * Maximum number of returned items, maximum 1000, default 1000
     * @param int $value
     * @return self
     */
    public function setLimit($value)
    {
        $this->obj->limit = $value;
        return $this;
    }

    /**
     * Get the final object.
     * @return GetDepositListReq
     */
    public function build()
    {
        return $this->obj;
    }
}
