<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Broker\Ndbroker;

use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Serializer;
use KuCoin\UniversalSDK\Internal\Interfaces\Request;

class ModifySubAccountApiReq implements Request
{
    /**
     * @var string[] $pathVarMapping
     * @Exclude()
     */
    public static $pathVarMapping = [];

    public function pathVarMapping()
    {
        return self::$pathVarMapping;
    }
    /**
     * Sub-account UID
     * @var string $uid
     * @Type("string")
     * @SerializedName("uid")
     */
    public $uid;
    /**
     * IP whitelist list, supports up to 20 IPs
     * @var string[] $ipWhitelist
     * @Type("string[]")
     * @SerializedName("ipWhitelist")
     */
    public $ipWhitelist;
    /**
     * [Permissions](https://www.kucoin.com/docs-new/doc-338144) group list (only General, Spot and Futures permissions can be set, such as \"General, Trade\").
     * @var string[] $permissions
     * @Type("string[]")
     * @SerializedName("permissions")
     */
    public $permissions;
    /**
     * apikey remarks (length 4~32)
     * @var string $label
     * @Type("string")
     * @SerializedName("label")
     */
    public $label;
    /**
     * Sub-account apiKey
     * @var string $apiKey
     * @Type("string")
     * @SerializedName("apiKey")
     */
    public $apiKey;

    private function __construct() {}

    /**
     * @param Serializer $serializer
     * @return string
     */
    public function jsonSerialize($serializer)
    {
        return $serializer->serialize($this, "json");
    }

    /**
     * @param string $json
     * @param Serializer $serializer
     * @return self
     */
    public static function jsonDeserialize($json, $serializer)
    {
        return $serializer->deserialize(
            $json,
            ModifySubAccountApiReq::class,
            "json"
        );
    }
    /**
     * Creates a new instance of the `ModifySubAccountApiReq` class.
     * The builder pattern allows step-by-step construction of a `ModifySubAccountApiReq` object.
     * @return ModifySubAccountApiReqBuilder
     */
    public static function builder()
    {
        return new ModifySubAccountApiReqBuilder(new self());
    }

    /**
     * Creates a new instance of the `ModifySubAccountApiReq` class with the given data.
     * Ensure that the keys in data match the target field names in the documentation,
     * rather than the variable names in the class.
     * @return self
     */
    public static function create(array $data)
    {
        $obj = new self();
        foreach ($data as $key => $value) {
            if (property_exists($obj, $key)) {
                $obj->$key = $value;
            }
        }
        return $obj;
    }
}

class ModifySubAccountApiReqBuilder
{
    /**
     * @var ModifySubAccountApiReq $obj
     */
    private $obj;

    public function __construct(ModifySubAccountApiReq $obj)
    {
        $this->obj = $obj;
    }
    /**
     * @param string $value Sub-account UID
     * @return self
     */
    public function setUid($value)
    {
        $this->obj->uid = $value;
        return $this;
    }

    /**
     * @param string[] $value IP whitelist list, supports up to 20 IPs
     * @return self
     */
    public function setIpWhitelist($value)
    {
        $this->obj->ipWhitelist = $value;
        return $this;
    }

    /**
     * @param string[] $value [Permissions](https://www.kucoin.com/docs-new/doc-338144) group list (only General, Spot and Futures permissions can be set, such as \"General, Trade\").
     * @return self
     */
    public function setPermissions($value)
    {
        $this->obj->permissions = $value;
        return $this;
    }

    /**
     * @param string $value apikey remarks (length 4~32)
     * @return self
     */
    public function setLabel($value)
    {
        $this->obj->label = $value;
        return $this;
    }

    /**
     * @param string $value Sub-account apiKey
     * @return self
     */
    public function setApiKey($value)
    {
        $this->obj->apiKey = $value;
        return $this;
    }

    /**
     * Get the final object.
     * @return ModifySubAccountApiReq
     */
    public function build()
    {
        return $this->obj;
    }
}
