// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package spotpublic

// MarketSnapshotDataMarketChange24h struct for MarketSnapshotDataMarketChange24h
type MarketSnapshotDataMarketChange24h struct {
	ChangePrice float64 `json:"changePrice,omitempty"`
	ChangeRate  float64 `json:"changeRate,omitempty"`
	High        float64 `json:"high,omitempty"`
	Low         float64 `json:"low,omitempty"`
	Open        float64 `json:"open,omitempty"`
	Vol         float64 `json:"vol,omitempty"`
	VolValue    float64 `json:"volValue,omitempty"`
}

// NewMarketSnapshotDataMarketChange24h instantiates a new MarketSnapshotDataMarketChange24h object
// This constructor will assign default values to properties that have it defined
func NewMarketSnapshotDataMarketChange24h(changePrice float64, changeRate float64, high float64, low float64, open float64, vol float64, volValue float64) *MarketSnapshotDataMarketChange24h {
	this := MarketSnapshotDataMarketChange24h{}
	this.ChangePrice = changePrice
	this.ChangeRate = changeRate
	this.High = high
	this.Low = low
	this.Open = open
	this.Vol = vol
	this.VolValue = volValue
	return &this
}

// NewMarketSnapshotDataMarketChange24hWithDefaults instantiates a new MarketSnapshotDataMarketChange24h object
// This constructor will only assign default values to properties that have it defined,
func NewMarketSnapshotDataMarketChange24hWithDefaults() *MarketSnapshotDataMarketChange24h {
	this := MarketSnapshotDataMarketChange24h{}
	return &this
}

func (o *MarketSnapshotDataMarketChange24h) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["changePrice"] = o.ChangePrice
	toSerialize["changeRate"] = o.ChangeRate
	toSerialize["high"] = o.High
	toSerialize["low"] = o.Low
	toSerialize["open"] = o.Open
	toSerialize["vol"] = o.Vol
	toSerialize["volValue"] = o.VolValue
	return toSerialize
}
