// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.order;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class BatchCancelStopOrderReq implements Request {
  /** Cancel the open order for the specified symbol */
  @JsonProperty("symbol")
  private String symbol;

  /**
   * The type of trading : TRADE（Spot）, MARGIN_TRADE (Cross Margin), MARGIN_ISOLATED_TRADE (Isolated
   * Margin).
   */
  @JsonProperty("tradeType")
  private String tradeType;

  /** Comma seperated order IDs. */
  @JsonProperty("orderIds")
  private String orderIds;
}
