// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class BatchAddOrdersSyncResp
    implements Response<BatchAddOrdersSyncResp, RestResponse<BatchAddOrdersSyncResp>> {
  /** */
  @JsonProperty("data")
  private List<BatchAddOrdersSyncData> data = new ArrayList<>();

  /** common response */
  @JsonIgnore private RestResponse<BatchAddOrdersSyncResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<BatchAddOrdersSyncResp> response) {
    this.commonResponse = response;
  }

  @JsonCreator
  public static BatchAddOrdersSyncResp fromJson(List<BatchAddOrdersSyncData> data) {
    // original response
    BatchAddOrdersSyncResp obj = new BatchAddOrdersSyncResp();
    obj.data = data;
    return obj;
  }
}
