// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.order;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class BatchAddOrdersOldResp
    implements Response<BatchAddOrdersOldResp, RestResponse<BatchAddOrdersOldResp>> {
  /** */
  @JsonProperty("data")
  private List<BatchAddOrdersOldData> data = new ArrayList<>();

  /** common response */
  @JsonIgnore private RestResponse<BatchAddOrdersOldResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<BatchAddOrdersOldResp> response) {
    this.commonResponse = response;
  }
}
