// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class CancelAllOrdersBySymbolResp
    implements Response<CancelAllOrdersBySymbolResp, RestResponse<CancelAllOrdersBySymbolResp>> {
  /** */
  @JsonProperty("data")
  private String data;

  /** common response */
  @JsonIgnore private RestResponse<CancelAllOrdersBySymbolResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<CancelAllOrdersBySymbolResp> response) {
    this.commonResponse = response;
  }

  @JsonCreator
  public static CancelAllOrdersBySymbolResp fromJson(String data) {
    // original response
    CancelAllOrdersBySymbolResp obj = new CancelAllOrdersBySymbolResp();
    obj.data = data;
    return obj;
  }

  @JsonValue
  public Object toJson() {
    return this.data;
  }
}
