// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.order;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOcoOrderDetailByOrderIdOrders {
  /** */
  @JsonProperty("id")
  private String id;

  /** */
  @JsonProperty("symbol")
  private String symbol;

  /** */
  @JsonProperty("side")
  private String side;

  /** */
  @JsonProperty("price")
  private String price;

  /** */
  @JsonProperty("stopPrice")
  private String stopPrice;

  /** */
  @JsonProperty("size")
  private String size;

  /** */
  @JsonProperty("status")
  private String status;
}
