// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetOcoOrderListItems {
  /**
   * The unique order ID generated by the trading system, which can be used later for further
   * actions such as canceling the order.
   */
  @JsonProperty("orderId")
  private String orderId;

  /** symbol */
  @JsonProperty("symbol")
  private String symbol;

  /** Client Order ID */
  @JsonProperty("clientOid")
  private String clientOid;

  /** Order placement time, milliseconds */
  @JsonProperty("orderTime")
  private Long orderTime;

  /** Order status: NEW: New, DONE: Completed, TRIGGERED: Triggered, CANCELED: Canceled */
  @JsonProperty("status")
  private StatusEnum status;

  public enum StatusEnum {
    /** New */
    NEW("NEW"),
    /** Completed */
    DONE("DONE"),
    /** Triggered */
    TRIGGERED("TRIGGERED"),
    /** Canceled */
    CANCELED("CANCELLED");

    private final String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
}
