// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.order;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ModifyOrderReq implements Request {
  /** One must be chose out of the old client order ID, orderId and clientOid */
  @JsonProperty("clientOid")
  private String clientOid;

  /** symbol */
  @JsonProperty("symbol")
  private String symbol;

  /** One must be chosen out of the old order id, orderId and clientOid */
  @JsonProperty("orderId")
  private String orderId;

  /** One must be chosen out of the modified price of the new order, newPrice and newSize */
  @JsonProperty("newPrice")
  private String newPrice;

  /** One must be chosen out of the modified size of the new order, newPrice and newSize */
  @JsonProperty("newSize")
  private String newSize;
}
