// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.margin.marginpublic;

public interface MarginPublicWs {

  /**
   * Index Price
   *
   * <p>Subscribe to this topic to get the index price for margin trading. The following ticker
   * symbols are supported: List of currently supported symbols.
   *
   * <p>push frequency: once every 1s
   */
  String indexPrice(String[] symbol, IndexPriceEvent.Callback callback);

  /**
   * Mark Price
   *
   * <p>Subscribe to this topic to get the mark price for margin trading. The following ticker
   * symbols are supported: List of currently supported symbols
   *
   * <p>push frequency: once every 1s
   */
  String markPrice(String[] symbol, MarkPriceEvent.Callback callback);

  /** Unsubscribe from topics */
  void unSubscribe(String id);

  /** Start websocket */
  void start();

  /** Stop websocket */
  void stop();
}
