<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Futures\Positions;

use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Serializer;
use KuCoin\UniversalSDK\Internal\Interfaces\Serializable;

class AddIsolatedMarginReq implements Serializable
{
    /**
     * @var string[] $pathVarMapping
     * @Exclude()
     */
    public static $pathVarMapping = [];

    public function pathVarMapping()
    {
        return self::$pathVarMapping;
    }
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     * @var string $symbol
     * @Type("string")
     * @SerializedName("symbol")
     */
    public $symbol;
    /**
     * Margin amount (min. margin amount≥0.00001667XBT）
     * @var float $margin
     * @Type("float")
     * @SerializedName("margin")
     */
    public $margin;
    /**
     * A unique ID generated by the user, to ensure the operation is processed by the system only once, The maximum length cannot exceed 36
     * @var string $bizNo
     * @Type("string")
     * @SerializedName("bizNo")
     */
    public $bizNo;

    private function __construct() {}

    /**
     * @param Serializer $serializer
     * @return string
     */
    public function jsonSerialize($serializer)
    {
        return $serializer->serialize($this, "json");
    }

    /**
     * @param string $json
     * @param Serializer $serializer
     * @return self
     */
    public static function jsonDeserialize($json, $serializer)
    {
        if ($json == null) {
            return new self();
        }
        return $serializer->deserialize(
            $json,
            AddIsolatedMarginReq::class,
            "json"
        );
    }
    /**
     * Creates a new instance of the `AddIsolatedMarginReq` class.
     * The builder pattern allows step-by-step construction of a `AddIsolatedMarginReq` object.
     * @return AddIsolatedMarginReqBuilder
     */
    public static function builder()
    {
        return new AddIsolatedMarginReqBuilder(new self());
    }

    /**
     * Creates a new instance of the `AddIsolatedMarginReq` class with the given data.
     * Ensure that the keys in data match the target field names in the documentation,
     * rather than the variable names in the class.
     * @return self
     */
    public static function create(array $data)
    {
        $obj = new self();
        foreach ($data as $key => $value) {
            if (property_exists($obj, $key)) {
                $obj->$key = $value;
            }
        }
        return $obj;
    }
}

class AddIsolatedMarginReqBuilder
{
    /**
     * @var AddIsolatedMarginReq $obj
     */
    private $obj;

    public function __construct(AddIsolatedMarginReq $obj)
    {
        $this->obj = $obj;
    }
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     * @param string $value
     * @return self
     */
    public function setSymbol($value)
    {
        $this->obj->symbol = $value;
        return $this;
    }

    /**
     * Margin amount (min. margin amount≥0.00001667XBT）
     * @param float $value
     * @return self
     */
    public function setMargin($value)
    {
        $this->obj->margin = $value;
        return $this;
    }

    /**
     * A unique ID generated by the user, to ensure the operation is processed by the system only once, The maximum length cannot exceed 36
     * @param string $value
     * @return self
     */
    public function setBizNo($value)
    {
        $this->obj->bizNo = $value;
        return $this;
    }

    /**
     * Get the final object.
     * @return AddIsolatedMarginReq
     */
    public function build()
    {
        return $this->obj;
    }
}
