<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Account\Withdrawal;

interface WithdrawalApi
{
    /**
     * Get Withdrawal Quotas
     *
     * This interface can obtain the withdrawal quota information of this currency.
     * @see: https://www.kucoin.com/docs-new/api-3470143
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | GENERAL    |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 20         |
     * +-----------------------+------------+
     */
    public function getWithdrawalQuotas(
        GetWithdrawalQuotasReq $req
    ): GetWithdrawalQuotasResp;

    /**
     * Withdraw (V3)
     *
     * Use this interface to withdraw the specified currency.
     * @see: https://www.kucoin.com/docs-new/api-3470146
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | WITHDRAWAL |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 5          |
     * +-----------------------+------------+
     */
    public function withdrawalV3(WithdrawalV3Req $req): WithdrawalV3Resp;

    /**
     * Cancel Withdrawal
     *
     * This interface can cancel the withdrawal. Only withdrawal requests with PROCESSING status can be canceled.
     * @see: https://www.kucoin.com/docs-new/api-3470144
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | WITHDRAWAL |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 20         |
     * +-----------------------+------------+
     */
    public function cancelWithdrawal(
        CancelWithdrawalReq $req
    ): CancelWithdrawalResp;

    /**
     * Get Withdrawal History
     *
     * Request a withdrawal list via this endpoint. Items are paginated and sorted to show the latest first. See the Pagination section for retrieving additional entries after the first page.
     * @see: https://www.kucoin.com/docs-new/api-3470145
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | GENERAL    |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 20         |
     * +-----------------------+------------+
     */
    public function getWithdrawalHistory(
        GetWithdrawalHistoryReq $req
    ): GetWithdrawalHistoryResp;

    /**
     * Get Withdrawal History By ID
     *
     * Request a withdrawal history by id via this endpoint.
     * @see: https://www.kucoin.com/docs-new/api-3471890
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | GENERAL    |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 20         |
     * +-----------------------+------------+
     */
    public function getWithdrawalHistoryById(
        GetWithdrawalHistoryByIdReq $req
    ): GetWithdrawalHistoryByIdResp;

    /**
     * Get Withdrawal History - Old
     *
     * Request a deposit list via this endpoint. Items are paginated and sorted to show the latest first. See the Pagination section for retrieving additional entries after the first page.
     * @deprecated
     * @see: https://www.kucoin.com/docs-new/api-3470308
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | GENERAL    |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 20         |
     * +-----------------------+------------+
     */
    public function getWithdrawalHistoryOld(
        GetWithdrawalHistoryOldReq $req
    ): GetWithdrawalHistoryOldResp;

    /**
     * Withdraw - V1
     *
     * Use this interface to withdraw the specified currency.
     * @deprecated
     * @see: https://www.kucoin.com/docs-new/api-3470310
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | WITHDRAWAL |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 5          |
     * +-----------------------+------------+
     */
    public function withdrawalV1(WithdrawalV1Req $req): WithdrawalV1Resp;
}
