// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';

export class GetWithdrawalHistoryByIdReq implements Serializable {
    /**
     * withdrawal ID
     */
    @Reflect.metadata('path', 'withdrawalId')
    withdrawalId?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `GetWithdrawalHistoryByIdReq` class.
     * The builder pattern allows step-by-step construction of a `GetWithdrawalHistoryByIdReq` object.
     */
    static builder(): GetWithdrawalHistoryByIdReqBuilder {
        return new GetWithdrawalHistoryByIdReqBuilder(new GetWithdrawalHistoryByIdReq());
    }

    /**
     * Creates a new instance of the `GetWithdrawalHistoryByIdReq` class with the given data.
     */
    static create(data: {
        /**
         * withdrawal ID
         */
        withdrawalId?: string;
    }): GetWithdrawalHistoryByIdReq {
        let obj = new GetWithdrawalHistoryByIdReq();
        obj.withdrawalId = data.withdrawalId;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetWithdrawalHistoryByIdReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetWithdrawalHistoryByIdReq {
        return plainToClassFromExist(new GetWithdrawalHistoryByIdReq(), jsonObject);
    }
}

export class GetWithdrawalHistoryByIdReqBuilder {
    constructor(readonly obj: GetWithdrawalHistoryByIdReq) {
        this.obj = obj;
    }
    /**
     * withdrawal ID
     */
    setWithdrawalId(value: string): GetWithdrawalHistoryByIdReqBuilder {
        this.obj.withdrawalId = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): GetWithdrawalHistoryByIdReq {
        return this.obj;
    }
}
