<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Viplending\Viplending;

use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Serializer;
use KuCoin\UniversalSDK\Internal\Interfaces\Serializable;

class GetLoanInfoMargins implements Serializable
{
    /**
     * @var string[] $pathVarMapping
     * @Exclude()
     */
    public static $pathVarMapping = [];

    public function pathVarMapping()
    {
        return self::$pathVarMapping;
    }
    /**
     * Margin Currency
     * @var string $marginCcy
     * @Type("string")
     * @SerializedName("marginCcy")
     */
    public $marginCcy;
    /**
     * Maintenance Quantity (Calculated with Margin Coefficient)
     * @var string $marginQty
     * @Type("string")
     * @SerializedName("marginQty")
     */
    public $marginQty;
    /**
     * Margin Coefficient return real-time margin discount rate to USDT
     * @var string $marginFactor
     * @Type("string")
     * @SerializedName("marginFactor")
     */
    public $marginFactor;

    private function __construct() {}

    /**
     * @param Serializer $serializer
     * @return string
     */
    public function jsonSerialize($serializer)
    {
        return $serializer->serialize($this, "json");
    }

    /**
     * @param string $json
     * @param Serializer $serializer
     * @return self
     */
    public static function jsonDeserialize($json, $serializer)
    {
        return $serializer->deserialize(
            $json,
            GetLoanInfoMargins::class,
            "json"
        );
    }
}
