// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.futures.market;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAllTickersResp
    implements Response<GetAllTickersResp, RestResponse<GetAllTickersResp>> {
  /** */
  @JsonProperty("data")
  private List<GetAllTickersData> data = new ArrayList<>();

  /** common response */
  @JsonIgnore private RestResponse<GetAllTickersResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<GetAllTickersResp> response) {
    this.commonResponse = response;
  }

  @JsonCreator
  public static GetAllTickersResp fromJson(List<GetAllTickersData> data) {
    // original response
    GetAllTickersResp obj = new GetAllTickersResp();
    obj.data = data;
    return obj;
  }
}
