// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.margin.marginprivate;

public interface MarginPrivateWs {

  /**
   * Get Cross Margin Position change
   *
   * <p>The system will push the change event when the position status changes, or push the current
   * debt message periodically when there is a liability.
   *
   * <p>push frequency: once every 4s
   */
  String crossMarginPosition(CrossMarginPositionEvent.Callback callback);

  /**
   * Get Isolated Margin Position change
   *
   * <p>The system will push the change event when the position status changes, or push the current
   * debt message periodically when there is a liability.
   *
   * <p>push frequency: real time
   */
  String isolatedMarginPosition(String symbol, IsolatedMarginPositionEvent.Callback callback);

  /** Unsubscribe from topics */
  void unSubscribe(String id);

  /** Start websocket */
  void start();

  /** Stop websocket */
  void stop();
}
