<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Spot\SpotPublic;
use KuCoin\UniversalSDK\Internal\Interfaces\WebSocketService;
use React\Promise\PromiseInterface;

class SpotPublicWsImpl implements SpotPublicWs
{
    /**@var WebSocketService $wsService*/
    private $wsService;

    public function __construct(WebSocketService $wsService)
    {
        $this->wsService = $wsService;
    }

    public function allTickers(callable $callback): PromiseInterface
    {
        $topicPrefix = "/market/ticker:all";

        $args = [];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            AllTickersEvent::createCallback($callback)
        );
    }

    public function callAuctionInfo(
        string $symbol,
        callable $callback
    ): PromiseInterface {
        $topicPrefix = "/callauction/callauctionData";

        $args = [$symbol];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            CallAuctionInfoEvent::createCallback($callback)
        );
    }

    public function callAuctionOrderbookLevel50(
        string $symbol,
        callable $callback
    ): PromiseInterface {
        $topicPrefix = "/callauction/level2Depth50";

        $args = [$symbol];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            CallAuctionOrderbookLevel50Event::createCallback($callback)
        );
    }

    public function klines(
        string $symbol,
        string $type,
        callable $callback
    ): PromiseInterface {
        $topicPrefix = "/market/candles";

        $args = [implode("_", [$symbol, $type])];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            KlinesEvent::createCallback($callback)
        );
    }

    public function marketSnapshot(
        string $market,
        callable $callback
    ): PromiseInterface {
        $topicPrefix = "/market/snapshot";

        $args = [$market];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            MarketSnapshotEvent::createCallback($callback)
        );
    }

    public function orderbookIncrement(
        array $symbol,
        callable $callback
    ): PromiseInterface {
        $topicPrefix = "/market/level2";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            OrderbookIncrementEvent::createCallback($callback)
        );
    }

    public function orderbookLevel1(
        array $symbol,
        callable $callback
    ): PromiseInterface {
        $topicPrefix = "/spotMarket/level1";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            OrderbookLevel1Event::createCallback($callback)
        );
    }

    public function orderbookLevel50(
        array $symbol,
        callable $callback
    ): PromiseInterface {
        $topicPrefix = "/spotMarket/level2Depth50";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            OrderbookLevel50Event::createCallback($callback)
        );
    }

    public function orderbookLevel5(
        array $symbol,
        callable $callback
    ): PromiseInterface {
        $topicPrefix = "/spotMarket/level2Depth5";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            OrderbookLevel5Event::createCallback($callback)
        );
    }

    public function symbolSnapshot(
        string $symbol,
        callable $callback
    ): PromiseInterface {
        $topicPrefix = "/market/snapshot";

        $args = [$symbol];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            SymbolSnapshotEvent::createCallback($callback)
        );
    }

    public function ticker(array $symbol, callable $callback): PromiseInterface
    {
        $topicPrefix = "/market/ticker";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            TickerEvent::createCallback($callback)
        );
    }

    public function trade(array $symbol, callable $callback): PromiseInterface
    {
        $topicPrefix = "/market/match";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            TradeEvent::createCallback($callback)
        );
    }

    public function unSubscribe(string $id): PromiseInterface
    {
        return $this->wsService->unsubscribe($id);
    }

    public function start(): PromiseInterface
    {
        return $this->wsService->start();
    }

    public function stop(): PromiseInterface
    {
        return $this->wsService->stop();
    }
}
