<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Spot\SpotPublic;
use KuCoin\UniversalSDK\Internal\Interfaces\WebSocketService;

interface SpotPublicWs
{
    /**
     * Get All Tickers
     * Subscribe to this topic to get pushes on all market symbol BBO changes.
     * push frequency: once every 100ms
     * @param callable $callback function(string $topic, string $subject, AllTickersEvent $data): void
     */
    public function allTickers(callable $callback): string;

    /**
     * Get Call Auction Info
     * Subscribe to this topic to get the specified symbol call auction info.
     * push frequency: once every 100ms
     * @param callable $callback function(string $topic, string $subject, CallAuctionInfoEvent $data): void
     */
    public function callAuctionInfo(string $symbol, callable $callback): string;

    /**
     * CallAuctionOrderbook - Level50
     * The system will return the call auction 50 best ask/bid orders data; if there is no change in the market, data will not be pushed
     * push frequency: once every 100ms
     * @param callable $callback function(string $topic, string $subject, CallAuctionOrderbookLevel50Event $data): void
     */
    public function callAuctionOrderbookLevel50(
        string $symbol,
        callable $callback
    ): string;

    /**
     * Klines
     * Subscribe to this topic to get K-Line data.
     * push frequency: real-time
     * @param callable $callback function(string $topic, string $subject, KlinesEvent $data): void
     */
    public function klines(
        string $symbol,
        string $type,
        callable $callback
    ): string;

    /**
     * Market Snapshot
     * Subscribe to this topic to get snapshot data for the entire market.
     * push frequency: once every 2s
     * @param callable $callback function(string $topic, string $subject, MarketSnapshotEvent $data): void
     */
    public function marketSnapshot(string $market, callable $callback): string;

    /**
     * Orderbook - Increment
     * The system will return the increment change orderbook data (all depths); a topic supports up to 100 symbols. If there is no change in the market, data will not be pushed
     * push frequency: real-time
     * @param callable $callback function(string $topic, string $subject, OrderbookIncrementEvent $data): void
     */
    public function orderbookIncrement(
        array $symbol,
        callable $callback
    ): string;

    /**
     * Orderbook - Level1
     * The system will return the 1 best ask/bid orders data; a topic supports up to 100 symbols. If there is no change in the market, data will not be pushed
     * push frequency: once every 10ms
     * @param callable $callback function(string $topic, string $subject, OrderbookLevel1Event $data): void
     */
    public function orderbookLevel1(array $symbol, callable $callback): string;

    /**
     * Orderbook - Level50
     * The system will return data for the 50 best ask/bid orders; a topic supports up to 100 symbols. If there is no change in the market, data will not be pushed
     * push frequency: once every 100ms
     * @param callable $callback function(string $topic, string $subject, OrderbookLevel50Event $data): void
     */
    public function orderbookLevel50(array $symbol, callable $callback): string;

    /**
     * Orderbook - Level5
     * The system will return the 5 best ask/bid orders data; a topic supports up to 100 symbols. If there is no change in the market, data will not be pushed
     * push frequency: once every 100ms
     * @param callable $callback function(string $topic, string $subject, OrderbookLevel5Event $data): void
     */
    public function orderbookLevel5(array $symbol, callable $callback): string;

    /**
     * Symbol Snapshot
     * Subscribe to get snapshot data for a single symbol.
     * push frequency: once every 2s
     * @param callable $callback function(string $topic, string $subject, SymbolSnapshotEvent $data): void
     */
    public function symbolSnapshot(string $symbol, callable $callback): string;

    /**
     * Get Ticker
     * Subscribe to this topic to get specified symbol pushes on BBO changes.
     * push frequency: once every 100ms
     * @param callable $callback function(string $topic, string $subject, TickerEvent $data): void
     */
    public function ticker(array $symbol, callable $callback): string;

    /**
     * Trade
     * Subscribe to this topic to get Level 3 matching event data flows. A topic supports up to 100 symbols.
     * push frequency: real-time
     * @param callable $callback function(string $topic, string $subject, TradeEvent $data): void
     */
    public function trade(array $symbol, callable $callback): string;

    /**
     * Unsubscribe from topics
     */
    public function unSubscribe(string $id);

    /**
     * Start websocket
     */
    public function start();

    /**
     * Stop websocket
     */
    public function stop();
}

class SpotPublicWsImpl implements SpotPublicWs
{
    /**@var WebSocketService $wsService*/
    private $wsService;

    public function __construct(WebSocketService $wsService)
    {
        $this->wsService = $wsService;
    }

    public function allTickers(callable $callback): string
    {
        $topicPrefix = "/market/ticker:all";

        $args = [];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new AllTickersEventCallbackWrapper($callback)
        );
    }

    public function callAuctionInfo(string $symbol, callable $callback): string
    {
        $topicPrefix = "/callauction/callauctionData";

        $args = [$symbol];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new CallAuctionInfoEventCallbackWrapper($callback)
        );
    }

    public function callAuctionOrderbookLevel50(
        string $symbol,
        callable $callback
    ): string {
        $topicPrefix = "/callauction/level2Depth50";

        $args = [$symbol];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new CallAuctionOrderbookLevel50EventCallbackWrapper($callback)
        );
    }

    public function klines(
        string $symbol,
        string $type,
        callable $callback
    ): string {
        $topicPrefix = "/market/candles";

        $args = [implode("_", [$symbol, $type])];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new KlinesEventCallbackWrapper($callback)
        );
    }

    public function marketSnapshot(string $market, callable $callback): string
    {
        $topicPrefix = "/market/snapshot";

        $args = [$market];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new MarketSnapshotEventCallbackWrapper($callback)
        );
    }

    public function orderbookIncrement(
        array $symbol,
        callable $callback
    ): string {
        $topicPrefix = "/market/level2";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new OrderbookIncrementEventCallbackWrapper($callback)
        );
    }

    public function orderbookLevel1(array $symbol, callable $callback): string
    {
        $topicPrefix = "/spotMarket/level1";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new OrderbookLevel1EventCallbackWrapper($callback)
        );
    }

    public function orderbookLevel50(array $symbol, callable $callback): string
    {
        $topicPrefix = "/spotMarket/level2Depth50";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new OrderbookLevel50EventCallbackWrapper($callback)
        );
    }

    public function orderbookLevel5(array $symbol, callable $callback): string
    {
        $topicPrefix = "/spotMarket/level2Depth5";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new OrderbookLevel5EventCallbackWrapper($callback)
        );
    }

    public function symbolSnapshot(string $symbol, callable $callback): string
    {
        $topicPrefix = "/market/snapshot";

        $args = [$symbol];

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new SymbolSnapshotEventCallbackWrapper($callback)
        );
    }

    public function ticker(array $symbol, callable $callback): string
    {
        $topicPrefix = "/market/ticker";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new TickerEventCallbackWrapper($callback)
        );
    }

    public function trade(array $symbol, callable $callback): string
    {
        $topicPrefix = "/market/match";

        $args = $symbol;

        return $this->wsService->subscribe(
            $topicPrefix,
            $args,
            new TradeEventCallbackWrapper($callback)
        );
    }

    public function unSubscribe(string $id)
    {
        return $this->wsService->unsubscribe($id);
    }

    public function start()
    {
        return $this->wsService->start();
    }

    public function stop()
    {
        return $this->wsService->stop();
    }
}
