// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.service;

import com.kucoin.universal.sdk.generate.copytrading.futures.FuturesApi;

public interface CopyTradingService {
  FuturesApi getFuturesApi();
}
