// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.service;

import com.kucoin.universal.sdk.generate.copytrading.futures.FuturesApi;
import com.kucoin.universal.sdk.generate.copytrading.futures.FuturesApiImpl;
import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class CopyTradingServiceImpl implements CopyTradingService {
  private Transport transport;
  private FuturesApi futures;

  public CopyTradingServiceImpl(Transport transport) {
    this.transport = transport;
    this.futures = new FuturesApiImpl(transport);
  }

  public FuturesApi getFuturesApi() {
    return this.futures;
  }
}
