// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.service;

import com.kucoin.universal.sdk.generate.futures.fundingfees.FundingFeesApi;
import com.kucoin.universal.sdk.generate.futures.fundingfees.FundingFeesApiImpl;
import com.kucoin.universal.sdk.generate.futures.market.MarketApi;
import com.kucoin.universal.sdk.generate.futures.market.MarketApiImpl;
import com.kucoin.universal.sdk.generate.futures.order.OrderApi;
import com.kucoin.universal.sdk.generate.futures.order.OrderApiImpl;
import com.kucoin.universal.sdk.generate.futures.positions.PositionsApi;
import com.kucoin.universal.sdk.generate.futures.positions.PositionsApiImpl;
import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class FuturesServiceImpl implements FuturesService {
  private Transport transport;
  private OrderApi order;
  private PositionsApi positions;
  private FundingFeesApi fundingFees;
  private MarketApi market;

  public FuturesServiceImpl(Transport transport) {
    this.transport = transport;
    this.order = new OrderApiImpl(transport);
    this.positions = new PositionsApiImpl(transport);
    this.fundingFees = new FundingFeesApiImpl(transport);
    this.market = new MarketApiImpl(transport);
  }

  public OrderApi getOrderApi() {
    return this.order;
  }

  public PositionsApi getPositionsApi() {
    return this.positions;
  }

  public FundingFeesApi getFundingFeesApi() {
    return this.fundingFees;
  }

  public MarketApi getMarketApi() {
    return this.market;
  }
}
