// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.broker.ndbroker;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class AddSubAccountApiResp
    implements Response<AddSubAccountApiResp, RestResponse<AddSubAccountApiResp>> {
  /** Sub-account UID */
  @JsonProperty("uid")
  private String uid;

  /** apikey remarks */
  @JsonProperty("label")
  private String label;

  /** apiKey */
  @JsonProperty("apiKey")
  private String apiKey;

  /** secretKey */
  @JsonProperty("secretKey")
  private String secretKey;

  /** apiVersion */
  @JsonProperty("apiVersion")
  private Integer apiVersion;

  /** [Permissions](https://www.kucoin.com/docs-new/doc-338144) group list */
  @JsonProperty("permissions")
  private List<String> permissions = new ArrayList<>();

  /** IP whitelist list */
  @JsonProperty("ipWhitelist")
  private List<String> ipWhitelist = new ArrayList<>();

  /** Creation time, Unix timestamp (milliseconds) */
  @JsonProperty("createdAt")
  private Long createdAt;

  /** common response */
  @JsonIgnore private RestResponse<AddSubAccountApiResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<AddSubAccountApiResp> response) {
    this.commonResponse = response;
  }
}
