// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.broker.ndbroker;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class TransferResp implements Response<TransferResp, RestResponse<TransferResp>> {
  /** */
  @JsonProperty("orderId")
  private String orderId;

  /** common response */
  @JsonIgnore private RestResponse<TransferResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<TransferResp> response) {
    this.commonResponse = response;
  }
}
