// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetKYCStatusReq implements Serializable {
    /**
     * Client uid, Use commas to separate multiple UIDs
     */
    clientUids?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `GetKYCStatusReq` class.
     * The builder pattern allows step-by-step construction of a `GetKYCStatusReq` object.
     */
    static builder(): GetKYCStatusReqBuilder {
        return new GetKYCStatusReqBuilder(new GetKYCStatusReq());
    }

    /**
     * Creates a new instance of the `GetKYCStatusReq` class with the given data.
     */
    static create(data: {
        /**
         * Client uid, Use commas to separate multiple UIDs
         */
        clientUids?: string;
    }): GetKYCStatusReq {
        let obj = new GetKYCStatusReq();
        obj.clientUids = data.clientUids;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetKYCStatusReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetKYCStatusReq {
        return plainToClassFromExist(new GetKYCStatusReq(), jsonObject);
    }
}

export class GetKYCStatusReqBuilder {
    constructor(readonly obj: GetKYCStatusReq) {
        this.obj = obj;
    }
    /**
     * Client uid, Use commas to separate multiple UIDs
     */
    setClientUids(value: string): GetKYCStatusReqBuilder {
        this.obj.clientUids = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): GetKYCStatusReq {
        return this.obj;
    }
}
