// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.margin.credit;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetPurchaseOrdersResp
    implements Response<GetPurchaseOrdersResp, RestResponse<GetPurchaseOrdersResp>> {
  /** Current Page */
  @JsonProperty("currentPage")
  private Integer currentPage;

  /** Page Size */
  @JsonProperty("pageSize")
  private Integer pageSize;

  /** Total Number */
  @JsonProperty("totalNum")
  private Integer totalNum;

  /** Total Pages */
  @JsonProperty("totalPage")
  private Integer totalPage;

  /** */
  @JsonProperty("items")
  private List<GetPurchaseOrdersItems> items = new ArrayList<>();

  /** common response */
  @JsonIgnore private RestResponse<GetPurchaseOrdersResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<GetPurchaseOrdersResp> response) {
    this.commonResponse = response;
  }
}
