<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Affiliate\Affiliate;
use KuCoin\UniversalSDK\Internal\Interfaces\Transport;

class AffiliateApiImpl implements AffiliateApi
{
    private $transport;

    public function __construct(Transport $transport)
    {
        $this->transport = $transport;
    }

    public function getAccount(): GetAccountResp
    {
        return $this->transport->call(
            "spot",
            false,
            "GET",
            "/api/v2/affiliate/inviter/statistics",
            null,
            GetAccountResp::class,
            false
        );
    }
}
