// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.futures.positions;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class AddIsolatedMarginResp
    implements Response<AddIsolatedMarginResp, RestResponse<AddIsolatedMarginResp>> {
  /** Position ID */
  @JsonProperty("id")
  private String id;

  /**
   * Symbol of the contract, Please refer to [Get Symbol endpoint:
   * symbol](https://www.kucoin.com/docs-new/api-3470220)
   */
  @JsonProperty("symbol")
  private String symbol;

  /** Auto deposit margin or not */
  @JsonProperty("autoDeposit")
  private Boolean autoDeposit;

  /** Maintenance margin requirement */
  @JsonProperty("maintMarginReq")
  private Double maintMarginReq;

  /** Risk limit */
  @JsonProperty("riskLimit")
  private Integer riskLimit;

  /** Leverage o the order */
  @JsonProperty("realLeverage")
  private Double realLeverage;

  /** Cross mode or not */
  @JsonProperty("crossMode")
  private Boolean crossMode;

  /** ADL ranking percentile */
  @JsonProperty("delevPercentage")
  private Double delevPercentage;

  /** Open time */
  @JsonProperty("openingTimestamp")
  private Long openingTimestamp;

  /** Current timestamp */
  @JsonProperty("currentTimestamp")
  private Long currentTimestamp;

  /** Current postion quantity */
  @JsonProperty("currentQty")
  private Integer currentQty;

  /** Current postion value */
  @JsonProperty("currentCost")
  private Double currentCost;

  /** Current commission */
  @JsonProperty("currentComm")
  private Double currentComm;

  /** Unrealised value */
  @JsonProperty("unrealisedCost")
  private Double unrealisedCost;

  /** Accumulated realised gross profit value */
  @JsonProperty("realisedGrossCost")
  private Double realisedGrossCost;

  /** Current realised position value */
  @JsonProperty("realisedCost")
  private Double realisedCost;

  /** Opened position or not */
  @JsonProperty("isOpen")
  private Boolean isOpen;

  /** Mark price */
  @JsonProperty("markPrice")
  private Double markPrice;

  /** Mark value */
  @JsonProperty("markValue")
  private Double markValue;

  /** Position value */
  @JsonProperty("posCost")
  private Double posCost;

  /** added margin */
  @JsonProperty("posCross")
  private Double posCross;

  /** Leverage margin */
  @JsonProperty("posInit")
  private Double posInit;

  /** Bankruptcy cost */
  @JsonProperty("posComm")
  private Double posComm;

  /** Funding fees paid out */
  @JsonProperty("posLoss")
  private Double posLoss;

  /** Position margin */
  @JsonProperty("posMargin")
  private Double posMargin;

  /** Maintenance margin */
  @JsonProperty("posMaint")
  private Double posMaint;

  /** Position margin */
  @JsonProperty("maintMargin")
  private Double maintMargin;

  /** Accumulated realised gross profit value */
  @JsonProperty("realisedGrossPnl")
  private Double realisedGrossPnl;

  /** Realised profit and loss */
  @JsonProperty("realisedPnl")
  private Double realisedPnl;

  /** Unrealised profit and loss */
  @JsonProperty("unrealisedPnl")
  private Double unrealisedPnl;

  /** Profit-loss ratio of the position */
  @JsonProperty("unrealisedPnlPcnt")
  private Double unrealisedPnlPcnt;

  /** Rate of return on investment */
  @JsonProperty("unrealisedRoePcnt")
  private Double unrealisedRoePcnt;

  /** Average entry price */
  @JsonProperty("avgEntryPrice")
  private Double avgEntryPrice;

  /** Liquidation price */
  @JsonProperty("liquidationPrice")
  private Double liquidationPrice;

  /** Bankruptcy price */
  @JsonProperty("bankruptPrice")
  private Double bankruptPrice;

  /** userId */
  @JsonProperty("userId")
  private Integer userId;

  /** Currency used to clear and settle the trades */
  @JsonProperty("settleCurrency")
  private String settleCurrency;

  /** common response */
  @JsonIgnore private RestResponse<AddIsolatedMarginResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<AddIsolatedMarginResp> response) {
    this.commonResponse = response;
  }
}
