// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.futures.positions;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCrossMarginRiskLimitReq implements Request {
  /**
   * Symbol of the contract. Please refer to [Get Symbol endpoint:
   * symbol](https://www.kucoin.com/docs-new/api-3470220), (You may add up to 50 symbols. Use a
   * halfwidth comma to each IP)
   */
  @JsonProperty("symbol")
  private String symbol;

  /**
   * The position opening amount, in the contract's settlement currency. Defaults to 10,000 in
   * margin currency for max position calculation. For USDT/USDC, it's 10,000 USD; for others, it's
   * 10,000 divided by the token's USDT price.
   */
  @JsonProperty("totalMargin")
  private String totalMargin;

  /**
   * Calculates the max position size at the specified leverage. Defaults to the symbol’s max cross
   * leverage.
   */
  @JsonProperty("leverage")
  private Integer leverage;
}
