<?php

namespace KuCoin\UniversalSDK\Model;

/**
 * Class WebSocketEvent
 * Defines the types of WebSocket events.
 */
class WebSocketEvent
{
    const EVENT_CONNECTED = 'EVENT_CONNECTED';
    const EVENT_DISCONNECTED = 'EVENT_DISCONNECTED';
    const EVENT_TRY_RECONNECT = 'EVENT_TRY_RECONNECT';
    const EVENT_MESSAGE_RECEIVED = 'EVENT_MESSAGE_RECEIVED';
    const EVENT_ERROR_RECEIVED = 'EVENT_ERROR_RECEIVED';
    const EVENT_PONG_RECEIVED = 'EVENT_PONG_RECEIVED';
    const EVENT_READ_BUFFER_FULL = 'EVENT_READ_BUFFER_FULL';
    const EVENT_WRITE_BUFFER_FULL = 'EVENT_WRITE_BUFFER_FULL';
    const EVENT_CALLBACK_ERROR = 'EVENT_CALLBACK_ERROR';
    const EVENT_RE_SUBSCRIBE_OK = 'EVENT_RE_SUBSCRIBE_OK';
    const EVENT_RE_SUBSCRIBE_ERROR = 'EVENT_RE_SUBSCRIBE_ERROR';
    const EVENT_CLIENT_FAIL = 'EVENT_CLIENT_FAIL';
    const EVENT_CLIENT_SHUTDOWN = 'EVENT_CLIENT_SHUTDOWN';
}