// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.withdrawal;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class WithdrawalV1Resp
    implements Response<WithdrawalV1Resp, RestResponse<WithdrawalV1Resp>> {
  /** Withdrawal id, a unique ID for a withdrawal */
  @JsonProperty("withdrawalId")
  private String withdrawalId;

  /** common response */
  @JsonIgnore private RestResponse<WithdrawalV1Resp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<WithdrawalV1Resp> response) {
    this.commonResponse = response;
  }
}
