// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.earn.earn;

import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class EarnApiImpl implements EarnApi {
  private final Transport transport;

  public EarnApiImpl(Transport transport) {
    this.transport = transport;
  }

  public PurchaseResp purchase(PurchaseReq req) {
    return this.transport.call(
        "spot", false, "POST", "/api/v1/earn/orders", req, PurchaseResp.class, false);
  }

  public GetRedeemPreviewResp getRedeemPreview(GetRedeemPreviewReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/earn/redeem-preview",
        req,
        GetRedeemPreviewResp.class,
        false);
  }

  public RedeemResp redeem(RedeemReq req) {
    return this.transport.call(
        "spot", false, "DELETE", "/api/v1/earn/orders", req, RedeemResp.class, false);
  }

  public GetSavingsProductsResp getSavingsProducts(GetSavingsProductsReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/earn/saving/products",
        req,
        GetSavingsProductsResp.class,
        false);
  }

  public GetPromotionProductsResp getPromotionProducts(GetPromotionProductsReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/earn/promotion/products",
        req,
        GetPromotionProductsResp.class,
        false);
  }

  public GetStakingProductsResp getStakingProducts(GetStakingProductsReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/earn/staking/products",
        req,
        GetStakingProductsResp.class,
        false);
  }

  public GetKcsStakingProductsResp getKcsStakingProducts(GetKcsStakingProductsReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/earn/kcs-staking/products",
        req,
        GetKcsStakingProductsResp.class,
        false);
  }

  public GetETHStakingProductsResp getETHStakingProducts(GetETHStakingProductsReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/earn/eth-staking/products",
        req,
        GetETHStakingProductsResp.class,
        false);
  }

  public GetAccountHoldingResp getAccountHolding(GetAccountHoldingReq req) {
    return this.transport.call(
        "spot", false, "GET", "/api/v1/earn/hold-assets", req, GetAccountHoldingResp.class, false);
  }
}
