// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.futures.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class AddTPSLOrderReq implements Request {
  /**
   * Unique order id created by users to identify their orders, the maximum length cannot exceed 40,
   * e.g. UUID, Only allows numbers, characters, underline(_), and separator(-)
   */
  @JsonProperty("clientOid")
  private String clientOid;

  /** specify if the order is to 'buy' or 'sell' */
  @JsonProperty("side")
  private SideEnum side;

  /**
   * Symbol of the contract, Please refer to [Get Symbol endpoint:
   * symbol](https://www.kucoin.com/docs-new/api-3470220)
   */
  @JsonProperty("symbol")
  private String symbol;

  /**
   * Used to calculate the margin to be frozen for the order. If you are to close the position, this
   * parameter is not required.
   */
  @JsonProperty("leverage")
  private Integer leverage;

  /** specify if the order is an 'limit' order or 'market' order */
  @JsonProperty("type")
  @Builder.Default
  private TypeEnum type = TypeEnum.LIMIT;

  /** remark for the order, length cannot exceed 100 utf8 characters */
  @JsonProperty("remark")
  private String remark;

  /** Either 'TP', 'IP' or 'MP' */
  @JsonProperty("stopPriceType")
  private StopPriceTypeEnum stopPriceType;

  /**
   * A mark to reduce the position size only. Set to false by default. Need to set the position size
   * when reduceOnly is true. If set to true, only the orders reducing the position size will be
   * executed. If the reduce-only order size exceeds the position size, the extra size will be
   * canceled.
   */
  @JsonProperty("reduceOnly")
  @Builder.Default
  private Boolean reduceOnly = false;

  /**
   * A mark to close the position. Set to false by default. If closeOrder is set to true, the system
   * will close the position and the position size will become 0. Side, Size and Leverage fields can
   * be left empty and the system will determine the side and size automatically.
   */
  @JsonProperty("closeOrder")
  @Builder.Default
  private Boolean closeOrder = false;

  /**
   * A mark to forcely hold the funds for an order, even though it's an order to reduce the position
   * size. This helps the order stay on the order book and not get canceled when the position size
   * changes. Set to false by default. The system will forcely freeze certain amount of funds for
   * this order, including orders whose direction is opposite to the current positions. This feature
   * is to ensure that the order won’t be canceled by the matching engine in such a circumstance
   * that not enough funds are frozen for the order.
   */
  @JsonProperty("forceHold")
  @Builder.Default
  private Boolean forceHold = false;

  /**
   * [Self Trade Prevention](https://www.kucoin.com/docs-new/doc-338146) is divided into these
   * strategies: CN, CO, CB. Not supported DC at the moment.
   */
  @JsonProperty("stp")
  private StpEnum stp;

  /** Margin mode: ISOLATED, CROSS, default: ISOLATED */
  @JsonProperty("marginMode")
  @Builder.Default
  private MarginModeEnum marginMode = MarginModeEnum.ISOLATED;

  /** Required for type is 'limit' order, indicating the operating price */
  @JsonProperty("price")
  private String price;

  /**
   * **Choose one of size, qty, valueQty**, Order size (Lot), must be a positive integer. The
   * quantity unit of coin-swap contracts is size(lot), and other units are not supported.
   */
  @JsonProperty("size")
  private Integer size;

  /**
   * Optional for type is 'limit' order, [Time in force](https://www.kucoin.com/docs-new/doc-338146)
   * is a special strategy used during trading, default is GTC
   */
  @JsonProperty("timeInForce")
  @Builder.Default
  private TimeInForceEnum timeInForce = TimeInForceEnum.GOODTILLCANCELED;

  /**
   * Optional for type is 'limit' order, post only flag, invalid when timeInForce is IOC. When
   * postOnly is true, not allowed choose hidden or iceberg. The post-only flag ensures that the
   * trader always pays the maker fee and provides liquidity to the order book. If any part of the
   * order is going to pay taker fee, the order will be fully rejected.
   */
  @JsonProperty("postOnly")
  @Builder.Default
  private Boolean postOnly = false;

  /**
   * Optional for type is 'limit' order, orders not displaying in order book. When hidden chose, not
   * allowed choose postOnly.
   */
  @JsonProperty("hidden")
  @Builder.Default
  private Boolean hidden = false;

  /**
   * Optional for type is 'limit' order, Only visible portion of the order is displayed in the order
   * book. When iceberg chose, not allowed choose postOnly.
   */
  @JsonProperty("iceberg")
  @Builder.Default
  private Boolean iceberg = false;

  /**
   * Optional for type is 'limit' order, The maximum visible size of an iceberg order. please place
   * order in size (lots), The units of qty (base currency) and valueQty (value) are not supported.
   * Need to be defined if iceberg is specified.
   */
  @JsonProperty("visibleSize")
  private String visibleSize;

  /** Take profit price */
  @JsonProperty("triggerStopUpPrice")
  private String triggerStopUpPrice;

  /** Stop loss price */
  @JsonProperty("triggerStopDownPrice")
  private String triggerStopDownPrice;

  /**
   * **Choose one of size, qty, valueQty**, Order size (Base currency) must be an integer multiple
   * of the multiplier. The unit of the quantity of coin-swap is size(lot), which is not supported
   */
  @JsonProperty("qty")
  private String qty;

  /**
   * **Choose one of size, qty, valueQty**, Order size (Value), USDS-Swap correspond to USDT or
   * USDC. The unit of the quantity of coin-swap is size(lot), which is not supported
   */
  @JsonProperty("valueQty")
  private String valueQty;

  public enum SideEnum {
    /** */
    BUY("buy"),
    /** */
    SELL("sell");

    private final String value;

    SideEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SideEnum fromValue(String value) {
      for (SideEnum b : SideEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public enum TypeEnum {
    /** limit order */
    LIMIT("limit"),
    /** market order */
    MARKET("market");

    private final String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public enum StopPriceTypeEnum {
    /**
     * TP for trade price, The last trade price is the last price at which an order was filled. This
     * price can be found in the latest match message.
     */
    TRADEPRICE("TP"),
    /**
     * MP for mark price, The mark price can be obtained through relevant OPEN API for index
     * services
     */
    MARKPRICE("MP"),
    /**
     * IP for index price, The index price can be obtained through relevant OPEN API for index
     * services
     */
    INDEXPRICE("IP");

    private final String value;

    StopPriceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StopPriceTypeEnum fromValue(String value) {
      for (StopPriceTypeEnum b : StopPriceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public enum StpEnum {
    /** Cancel new, Cancel the new order */
    CN("CN"),
    /** Cancel old, Cancel the old order */
    CO("CO"),
    /** Cancel both, Cancel both sides */
    CB("CB");

    private final String value;

    StpEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StpEnum fromValue(String value) {
      for (StpEnum b : StpEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public enum MarginModeEnum {
    /** */
    ISOLATED("ISOLATED"),
    /** */
    CROSS("CROSS");

    private final String value;

    MarginModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MarginModeEnum fromValue(String value) {
      for (MarginModeEnum b : MarginModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public enum TimeInForceEnum {
    /**
     * order remains open on the order book until canceled. This is the default type if the field is
     * left empty.
     */
    GOODTILLCANCELED("GTC"),
    /**
     * being matched or not, the remaining size of the order will be instantly canceled instead of
     * entering the order book.
     */
    IMMEDIATEORCANCEL("IOC");

    private final String value;

    TimeInForceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TimeInForceEnum fromValue(String value) {
      for (TimeInForceEnum b : TimeInForceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
}
