<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Spot\Order;

use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Serializer;
use KuCoin\UniversalSDK\Internal\Interfaces\Request;

class CancelPartialOrderReq implements Request
{
    /**
     * @var string[] $pathVarMapping
     * @Exclude()
     */
    public static $pathVarMapping = [
        "orderId" => "orderId",
    ];

    public function pathVarMapping()
    {
        return self::$pathVarMapping;
    }
    /**
     * The unique order id generated by the trading system
     * @var string|null $orderId
     * @Type("string")
     * @SerializedName("orderId")
     * @Exclude()
     */
    public $orderId;
    /**
     * symbol
     * @var string|null $symbol
     * @Type("string")
     * @SerializedName("symbol")
     */
    public $symbol;
    /**
     * The size you want cancel
     * @var string|null $cancelSize
     * @Type("string")
     * @SerializedName("cancelSize")
     */
    public $cancelSize;

    private function __construct() {}

    /**
     * @param Serializer $serializer
     * @return string
     */
    public function jsonSerialize($serializer)
    {
        return $serializer->serialize($this, "json");
    }

    /**
     * @param string $json
     * @param Serializer $serializer
     * @return self
     */
    public static function jsonDeserialize($json, $serializer)
    {
        return $serializer->deserialize(
            $json,
            CancelPartialOrderReq::class,
            "json"
        );
    }
    /**
     * Creates a new instance of the `CancelPartialOrderReq` class.
     * The builder pattern allows step-by-step construction of a `CancelPartialOrderReq` object.
     * @return CancelPartialOrderReqBuilder
     */
    public static function builder()
    {
        return new CancelPartialOrderReqBuilder(new self());
    }

    /**
     * Creates a new instance of the `CancelPartialOrderReq` class with the given data.
     * Ensure that the keys in data match the target field names in the documentation,
     * rather than the variable names in the class.
     * @return self
     */
    public static function create(array $data)
    {
        $obj = new self();
        foreach ($data as $key => $value) {
            if (property_exists($obj, $key)) {
                $obj->$key = $value;
            }
        }
        return $obj;
    }
}

class CancelPartialOrderReqBuilder
{
    /**
     * @var CancelPartialOrderReq $obj
     */
    private $obj;

    public function __construct(CancelPartialOrderReq $obj)
    {
        $this->obj = $obj;
    }
    /**
     * @param string $value The unique order id generated by the trading system
     * @return self
     */
    public function setOrderId($value)
    {
        $this->obj->orderId = $value;
        return $this;
    }

    /**
     * @param string $value symbol
     * @return self
     */
    public function setSymbol($value)
    {
        $this->obj->symbol = $value;
        return $this;
    }

    /**
     * @param string $value The size you want cancel
     * @return self
     */
    public function setCancelSize($value)
    {
        $this->obj->cancelSize = $value;
        return $this;
    }

    /**
     * Get the final object.
     * @return CancelPartialOrderReq
     */
    public function build()
    {
        return $this->obj;
    }
}
