<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Spot\Order;

use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Serializer;
use KuCoin\UniversalSDK\Internal\Interfaces\Response;
use KuCoin\UniversalSDK\Model\RestResponse;

class CancelOrderByClientOidSyncResp implements Response
{
    /**
     * Client Order Id，unique identifier created by the user
     * @var string $clientOid
     * @Type("string")
     * @SerializedName("clientOid")
     */
    public $clientOid;
    /**
     * original order size
     * @var string $originSize
     * @Type("string")
     * @SerializedName("originSize")
     */
    public $originSize;
    /**
     * deal size
     * @var string $dealSize
     * @Type("string")
     * @SerializedName("dealSize")
     */
    public $dealSize;
    /**
     * remain size
     * @var string $remainSize
     * @Type("string")
     * @SerializedName("remainSize")
     */
    public $remainSize;
    /**
     * Cumulative canceled size
     * @var string $canceledSize
     * @Type("string")
     * @SerializedName("canceledSize")
     */
    public $canceledSize;
    /**
     * Order Status. open：order is active; done：order has been completed
     * - 'open' : order is active
     * - 'done' : order has been completed
     * @var string $status
     * @Type("string")
     * @SerializedName("status")
     */
    public $status;

    /**
     * common response
     * @Exclude()
     * @var RestResponse $commonResponse
     */
    public $commonResponse;

    public function setCommonResponse($response): void
    {
        $this->commonResponse = $response;
    }

    private function __construct() {}

    /**
     * @param Serializer $serializer
     * @return string
     */
    public function jsonSerialize($serializer)
    {
        return $serializer->serialize($this, "json");
    }

    /**
     * @param string $json
     * @param Serializer $serializer
     * @return self
     */
    public static function jsonDeserialize($json, $serializer)
    {
        if ($json === null) {
            return new self();
        }
        return $serializer->deserialize(
            $json,
            CancelOrderByClientOidSyncResp::class,
            "json"
        );
    }
}
