<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Spot\Order;

use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Serializer;
use KuCoin\UniversalSDK\Internal\Interfaces\Response;
use KuCoin\UniversalSDK\Model\RestResponse;

class GetOcoOrderListResp implements Response
{
    /**
     *
     * @var int $currentPage
     * @Type("int")
     * @SerializedName("currentPage")
     */
    public $currentPage;
    /**
     *
     * @var int $pageSize
     * @Type("int")
     * @SerializedName("pageSize")
     */
    public $pageSize;
    /**
     *
     * @var int $totalNum
     * @Type("int")
     * @SerializedName("totalNum")
     */
    public $totalNum;
    /**
     *
     * @var int $totalPage
     * @Type("int")
     * @SerializedName("totalPage")
     */
    public $totalPage;
    /**
     *
     * @var GetOcoOrderListItems[] $items
     * @Type("array<KuCoin\UniversalSDK\Generate\Spot\Order\GetOcoOrderListItems>")
     * @SerializedName("items")
     */
    public $items;

    /**
     * common response
     * @Exclude()
     * @var RestResponse $commonResponse
     */
    public $commonResponse;

    public function setCommonResponse($response): void
    {
        $this->commonResponse = $response;
    }

    private function __construct() {}

    /**
     * @param Serializer $serializer
     * @return string
     */
    public function jsonSerialize($serializer)
    {
        return $serializer->serialize($this, "json");
    }

    /**
     * @param string $json
     * @param Serializer $serializer
     * @return self
     */
    public static function jsonDeserialize($json, $serializer)
    {
        return $serializer->deserialize(
            $json,
            GetOcoOrderListResp::class,
            "json"
        );
    }
}
