// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Transport } from '@internal/interfaces/transport';
import { GetAnnouncementsResp } from './model_get_announcements_resp';
import { GetTradeHistoryResp } from './model_get_trade_history_resp';
import { Get24hrStatsReq } from './model_get24hr_stats_req';
import { GetServiceStatusResp } from './model_get_service_status_resp';
import { GetAllSymbolsReq } from './model_get_all_symbols_req';
import { GetCallAuctionPartOrderBookReq } from './model_get_call_auction_part_order_book_req';
import { GetCallAuctionPartOrderBookResp } from './model_get_call_auction_part_order_book_resp';
import { GetTickerReq } from './model_get_ticker_req';
import { GetClientIPAddressResp } from './model_get_client_ip_address_resp';
import { GetPrivateTokenResp } from './model_get_private_token_resp';
import { GetFiatPriceResp } from './model_get_fiat_price_resp';
import { GetPartOrderBookReq } from './model_get_part_order_book_req';
import { GetSymbolReq } from './model_get_symbol_req';
import { GetSymbolResp } from './model_get_symbol_resp';
import { GetFullOrderBookResp } from './model_get_full_order_book_resp';
import { GetTickerResp } from './model_get_ticker_resp';
import { GetFullOrderBookReq } from './model_get_full_order_book_req';
import { GetAllSymbolsResp } from './model_get_all_symbols_resp';
import { GetPublicTokenResp } from './model_get_public_token_resp';
import { GetTradeHistoryReq } from './model_get_trade_history_req';
import { GetMarketListResp } from './model_get_market_list_resp';
import { GetCallAuctionInfoResp } from './model_get_call_auction_info_resp';
import { GetCallAuctionInfoReq } from './model_get_call_auction_info_req';
import { GetCurrencyReq } from './model_get_currency_req';
import { GetAllCurrenciesResp } from './model_get_all_currencies_resp';
import { Get24hrStatsResp } from './model_get24hr_stats_resp';
import { GetKlinesReq } from './model_get_klines_req';
import { GetCurrencyResp } from './model_get_currency_resp';
import { GetPartOrderBookResp } from './model_get_part_order_book_resp';
import { GetFiatPriceReq } from './model_get_fiat_price_req';
import { GetAllTickersResp } from './model_get_all_tickers_resp';
import { GetServerTimeResp } from './model_get_server_time_resp';
import { GetAnnouncementsReq } from './model_get_announcements_req';
import { GetKlinesResp } from './model_get_klines_resp';

export interface MarketAPI {
    /**
     * getAnnouncements Get Announcements
     * Description: This interface can obtain the latest news announcements, and the default page search is for announcements within a month.
     * Documentation: https://www.kucoin.com/docs-new/api-3470157
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 20     |
     * +-----------------------+--------+
     */
    getAnnouncements(req: GetAnnouncementsReq): Promise<GetAnnouncementsResp>;

    /**
     * getCurrency Get Currency
     * Description: Request the currency details of a specified currency via this endpoint.
     * Documentation: https://www.kucoin.com/docs-new/api-3470155
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 3      |
     * +-----------------------+--------+
     */
    getCurrency(req: GetCurrencyReq): Promise<GetCurrencyResp>;

    /**
     * getAllCurrencies Get All Currencies
     * Description: Request a currency list via this endpoint. Not all currencies can currently be used for trading.
     * Documentation: https://www.kucoin.com/docs-new/api-3470152
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 3      |
     * +-----------------------+--------+
     */
    getAllCurrencies(): Promise<GetAllCurrenciesResp>;

    /**
     * getSymbol Get Symbol
     * Description: Request detailed currency pairs for trading via this endpoint. If you want to get the market information of the trading symbol, please use Get All Tickers.
     * Documentation: https://www.kucoin.com/docs-new/api-3470159
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 4      |
     * +-----------------------+--------+
     */
    getSymbol(req: GetSymbolReq): Promise<GetSymbolResp>;

    /**
     * getAllSymbols Get All Symbols
     * Description: Request a list of available currency pairs for trading via this endpoint. If you want to get the market information of the trading symbol, please use Get All Tickers.
     * Documentation: https://www.kucoin.com/docs-new/api-3470154
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 4      |
     * +-----------------------+--------+
     */
    getAllSymbols(req: GetAllSymbolsReq): Promise<GetAllSymbolsResp>;

    /**
     * getTicker Get Ticker
     * Description: Request Level 1 Market Data via this endpoint. The returned value includes the best bid price and size, the best ask price and size, as well as the last traded price and the last traded size.
     * Documentation: https://www.kucoin.com/docs-new/api-3470160
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 2      |
     * +-----------------------+--------+
     */
    getTicker(req: GetTickerReq): Promise<GetTickerResp>;

    /**
     * getAllTickers Get All Tickers
     * Description: Request market tickers for all the trading pairs in the market (including 24h volume); takes a snapshot every 2 seconds.  On the rare occasion that we change the currency name, if you still want the changed symbol name, you can use the symbolName field instead of the symbol field via “Get all tickers” endpoint.
     * Documentation: https://www.kucoin.com/docs-new/api-3470167
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 15     |
     * +-----------------------+--------+
     */
    getAllTickers(): Promise<GetAllTickersResp>;

    /**
     * getTradeHistory Get Trade History
     * Description: Request the trade history of the specified symbol via this endpoint. The returned quantity is the last 100 transaction records.
     * Documentation: https://www.kucoin.com/docs-new/api-3470162
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 3      |
     * +-----------------------+--------+
     */
    getTradeHistory(req: GetTradeHistoryReq): Promise<GetTradeHistoryResp>;

    /**
     * getKlines Get Klines
     * Description: Get the symbol’s candlestick chart. Data are returned in grouped buckets based on requested type. For each query, the system will return at most 1500 pieces of data. To obtain more data, please page the data by time.
     * Documentation: https://www.kucoin.com/docs-new/api-3470163
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 3      |
     * +-----------------------+--------+
     */
    getKlines(req: GetKlinesReq): Promise<GetKlinesResp>;

    /**
     * getPartOrderBook Get Part OrderBook
     * Description: Query for part orderbook depth data. (aggregated by price). It is recommended that you request via this endpoint, as the system response will be faster and consume less traffic.
     * Documentation: https://www.kucoin.com/docs-new/api-3470165
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 2      |
     * +-----------------------+--------+
     */
    getPartOrderBook(req: GetPartOrderBookReq): Promise<GetPartOrderBookResp>;

    /**
     * getFullOrderBook Get Full OrderBook
     * Description: Query for Full orderbook depth data (aggregated by price). It is generally used by professional traders because it uses more server resources and traffic, and we have strict access rate limit control.  To maintain an up-to-date Order Book, please use Websocket incremental feed after retrieving the OrderBook.
     * Documentation: https://www.kucoin.com/docs-new/api-3470164
     * +-----------------------+---------+
     * | Extra API Info        | Value   |
     * +-----------------------+---------+
     * | API-DOMAIN            | SPOT    |
     * | API-CHANNEL           | PRIVATE |
     * | API-PERMISSION        | GENERAL |
     * | API-RATE-LIMIT-POOL   | SPOT    |
     * | API-RATE-LIMIT-WEIGHT | 3       |
     * +-----------------------+---------+
     */
    getFullOrderBook(req: GetFullOrderBookReq): Promise<GetFullOrderBookResp>;

    /**
     * getCallAuctionPartOrderBook Get Call Auction Part OrderBook
     * Description: Query for call auction part orderbook depth data. (aggregated by price). It is recommended that you request via this endpoint, as the system response will be faster and consume less traffic.
     * Documentation: https://www.kucoin.com/docs-new/api-3471564
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 2      |
     * +-----------------------+--------+
     */
    getCallAuctionPartOrderBook(
        req: GetCallAuctionPartOrderBookReq,
    ): Promise<GetCallAuctionPartOrderBookResp>;

    /**
     * getCallAuctionInfo Get Call Auction Info
     * Description: Get call auction data, This interface will return the following information for the specified symbol during the call auction phase: estimated transaction price, estimated transaction quantity, bid price range, and ask price range.
     * Documentation: https://www.kucoin.com/docs-new/api-3471565
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 2      |
     * +-----------------------+--------+
     */
    getCallAuctionInfo(req: GetCallAuctionInfoReq): Promise<GetCallAuctionInfoResp>;

    /**
     * getFiatPrice Get Fiat Price
     * Description: Request the fiat price of the currencies for the available trading pairs via this endpoint.
     * Documentation: https://www.kucoin.com/docs-new/api-3470153
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 3      |
     * +-----------------------+--------+
     */
    getFiatPrice(req: GetFiatPriceReq): Promise<GetFiatPriceResp>;

    /**
     * get24hrStats Get 24hr stats
     * Description: Request the statistics of the specified ticker in the last 24 hours via this endpoint.
     * Documentation: https://www.kucoin.com/docs-new/api-3470161
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 15     |
     * +-----------------------+--------+
     */
    get24hrStats(req: Get24hrStatsReq): Promise<Get24hrStatsResp>;

    /**
     * getMarketList Get Market List
     * Description: Request via this endpoint the transaction currency for the entire trading market.
     * Documentation: https://www.kucoin.com/docs-new/api-3470166
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 3      |
     * +-----------------------+--------+
     */
    getMarketList(): Promise<GetMarketListResp>;

    /**
     * getClientIPAddress Get Client IP Address
     * Description: Get the server time.
     * Documentation: https://www.kucoin.com/docs-new/api-3471123
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 0      |
     * +-----------------------+--------+
     */
    getClientIPAddress(): Promise<GetClientIPAddressResp>;

    /**
     * getServerTime Get Server Time
     * Description: Get the server time.
     * Documentation: https://www.kucoin.com/docs-new/api-3470156
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 3      |
     * +-----------------------+--------+
     */
    getServerTime(): Promise<GetServerTimeResp>;

    /**
     * getServiceStatus Get Service Status
     * Description: Get the service status.
     * Documentation: https://www.kucoin.com/docs-new/api-3470158
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 3      |
     * +-----------------------+--------+
     */
    getServiceStatus(): Promise<GetServiceStatusResp>;

    /**
     * getPublicToken Get Public Token - Spot/Margin
     * Description: This interface can obtain the token required for Websocket to establish a Spot/Margin connection. If you need use public channels (e.g. all public market data), please make request as follows to obtain the server list and public token
     * Documentation: https://www.kucoin.com/docs-new/api-3470294
     * +-----------------------+--------+
     * | Extra API Info        | Value  |
     * +-----------------------+--------+
     * | API-DOMAIN            | SPOT   |
     * | API-CHANNEL           | PUBLIC |
     * | API-PERMISSION        | NULL   |
     * | API-RATE-LIMIT-POOL   | PUBLIC |
     * | API-RATE-LIMIT-WEIGHT | 10     |
     * +-----------------------+--------+
     */
    getPublicToken(): Promise<GetPublicTokenResp>;

    /**
     * getPrivateToken Get Private Token - Spot/Margin
     * Description: This interface can obtain the token required for Websocket to establish a Spot/Margin private connection. If you need use private channels (e.g. account balance notice), please make request as follows to obtain the server list and private token
     * Documentation: https://www.kucoin.com/docs-new/api-3470295
     * +-----------------------+---------+
     * | Extra API Info        | Value   |
     * +-----------------------+---------+
     * | API-DOMAIN            | SPOT    |
     * | API-CHANNEL           | PRIVATE |
     * | API-PERMISSION        | GENERAL |
     * | API-RATE-LIMIT-POOL   | SPOT    |
     * | API-RATE-LIMIT-WEIGHT | 10      |
     * +-----------------------+---------+
     */
    getPrivateToken(): Promise<GetPrivateTokenResp>;
}

export class MarketAPIImpl implements MarketAPI {
    constructor(private transport: Transport) {}

    getAnnouncements(req: GetAnnouncementsReq): Promise<GetAnnouncementsResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v3/announcements',
            req,
            GetAnnouncementsResp,
            false,
        );
    }

    getCurrency(req: GetCurrencyReq): Promise<GetCurrencyResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v3/currencies/{currency}',
            req,
            GetCurrencyResp,
            false,
        );
    }

    getAllCurrencies(): Promise<GetAllCurrenciesResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v3/currencies',
            null,
            GetAllCurrenciesResp,
            false,
        );
    }

    getSymbol(req: GetSymbolReq): Promise<GetSymbolResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v2/symbols/{symbol}',
            req,
            GetSymbolResp,
            false,
        );
    }

    getAllSymbols(req: GetAllSymbolsReq): Promise<GetAllSymbolsResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v2/symbols',
            req,
            GetAllSymbolsResp,
            false,
        );
    }

    getTicker(req: GetTickerReq): Promise<GetTickerResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/market/orderbook/level1',
            req,
            GetTickerResp,
            false,
        );
    }

    getAllTickers(): Promise<GetAllTickersResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/market/allTickers',
            null,
            GetAllTickersResp,
            false,
        );
    }

    getTradeHistory(req: GetTradeHistoryReq): Promise<GetTradeHistoryResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/market/histories',
            req,
            GetTradeHistoryResp,
            false,
        );
    }

    getKlines(req: GetKlinesReq): Promise<GetKlinesResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/market/candles',
            req,
            GetKlinesResp,
            false,
        );
    }

    getPartOrderBook(req: GetPartOrderBookReq): Promise<GetPartOrderBookResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/market/orderbook/level2_{size}',
            req,
            GetPartOrderBookResp,
            false,
        );
    }

    getFullOrderBook(req: GetFullOrderBookReq): Promise<GetFullOrderBookResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v3/market/orderbook/level2',
            req,
            GetFullOrderBookResp,
            false,
        );
    }

    getCallAuctionPartOrderBook(
        req: GetCallAuctionPartOrderBookReq,
    ): Promise<GetCallAuctionPartOrderBookResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/market/orderbook/callauction/level2_{size}',
            req,
            GetCallAuctionPartOrderBookResp,
            false,
        );
    }

    getCallAuctionInfo(req: GetCallAuctionInfoReq): Promise<GetCallAuctionInfoResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/market/callauctionData',
            req,
            GetCallAuctionInfoResp,
            false,
        );
    }

    getFiatPrice(req: GetFiatPriceReq): Promise<GetFiatPriceResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/prices',
            req,
            GetFiatPriceResp,
            false,
        );
    }

    get24hrStats(req: Get24hrStatsReq): Promise<Get24hrStatsResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/market/stats',
            req,
            Get24hrStatsResp,
            false,
        );
    }

    getMarketList(): Promise<GetMarketListResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/markets',
            null,
            GetMarketListResp,
            false,
        );
    }

    getClientIPAddress(): Promise<GetClientIPAddressResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/my-ip',
            null,
            GetClientIPAddressResp,
            false,
        );
    }

    getServerTime(): Promise<GetServerTimeResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/timestamp',
            null,
            GetServerTimeResp,
            false,
        );
    }

    getServiceStatus(): Promise<GetServiceStatusResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/status',
            null,
            GetServiceStatusResp,
            false,
        );
    }

    getPublicToken(): Promise<GetPublicTokenResp> {
        return this.transport.call(
            'spot',
            false,
            'POST',
            '/api/v1/bullet-public',
            null,
            GetPublicTokenResp,
            false,
        );
    }

    getPrivateToken(): Promise<GetPrivateTokenResp> {
        return this.transport.call(
            'spot',
            false,
            'POST',
            '/api/v1/bullet-private',
            null,
            GetPrivateTokenResp,
            false,
        );
    }
}
