// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetAllCurrenciesDataChains implements Serializable {
    /**
     * Chain name of currency
     */
    chainName: string;

    /**
     * Minimum withdrawal amount
     */
    withdrawalMinSize: string;

    /**
     * Minimum deposit amount
     */
    depositMinSize?: string;

    /**
     * Withdraw fee rate
     */
    withdrawFeeRate: string;

    /**
     * Minimum fees charged for withdrawal
     */
    withdrawalMinFee: string;

    /**
     * Withdrawal support or not
     */
    isWithdrawEnabled: boolean;

    /**
     * Deposit support or not
     */
    isDepositEnabled: boolean;

    /**
     * Number of block confirmations
     */
    confirms: number;

    /**
     * The number of blocks (confirmations) for advance on-chain verification
     */
    preConfirms: number;

    /**
     * Contract address
     */
    contractAddress: string;

    /**
     * Withdrawal precision bit, indicating the maximum supported length after the decimal point of the withdrawal amount
     */
    withdrawPrecision: number;

    /**
     * Maximum amount of single withdrawal
     */
    maxWithdraw?: string;

    /**
     * Maximum amount of single deposit (only applicable to Lightning Network)
     */
    maxDeposit?: string;

    /**
     * Need for memo/tag or not
     */
    needTag: boolean;

    /**
     * Chain id of currency
     */
    chainId: string;

    /**
     * Deposit fee rate (some currencies have this param; the default is empty)
     */
    depositFeeRate?: string;

    /**
     * Withdraw max. fee (some currencies have this param; the default is empty)
     */
    withdrawMaxFee?: string;

    /**
     *
     */
    depositTierFee?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {
        // @ts-ignore
        this.chainName = null;
        // @ts-ignore
        this.withdrawalMinSize = null;
        // @ts-ignore
        this.withdrawFeeRate = null;
        // @ts-ignore
        this.withdrawalMinFee = null;
        // @ts-ignore
        this.isWithdrawEnabled = null;
        // @ts-ignore
        this.isDepositEnabled = null;
        // @ts-ignore
        this.confirms = null;
        // @ts-ignore
        this.preConfirms = null;
        // @ts-ignore
        this.contractAddress = null;
        // @ts-ignore
        this.withdrawPrecision = null;
        // @ts-ignore
        this.needTag = null;
        // @ts-ignore
        this.chainId = null;
    }
    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetAllCurrenciesDataChains {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetAllCurrenciesDataChains {
        return plainToClassFromExist(new GetAllCurrenciesDataChains(), jsonObject);
    }
}
