// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.transfer;

public interface TransferApi {
  /**
   * Get Transfer Quotas
   *
   * <p>This endpoint returns the transferable balance of a specified account.
   *
   * <p>Extra API Info:
   *
   * <ul>
   *   <li>API-DOMAIN : SPOT
   *   <li>API-CHANNEL : PRIVATE
   *   <li>API-PERMISSION : GENERAL
   *   <li>API-RATE-LIMIT-POOL : MANAGEMENT
   *   <li>API-RATE-LIMIT-WEIGHT : 20
   * </ul>
   *
   * @see <a href="https://www.kucoin.com/docs-new/api-3470148">docs</a>
   */
  GetTransferQuotasResp getTransferQuotas(GetTransferQuotasReq req);

  /**
   * Flex Transfer
   *
   * <p>This interface can be used for transfers between master- and sub-accounts and transfers
   *
   * <p>Extra API Info:
   *
   * <ul>
   *   <li>API-DOMAIN : SPOT
   *   <li>API-CHANNEL : PRIVATE
   *   <li>API-PERMISSION : FLEXTRANSFERS
   *   <li>API-RATE-LIMIT-POOL : MANAGEMENT
   *   <li>API-RATE-LIMIT-WEIGHT : 4
   * </ul>
   *
   * @see <a href="https://www.kucoin.com/docs-new/api-3470147">docs</a>
   */
  FlexTransferResp flexTransfer(FlexTransferReq req);

  /**
   * Sub-account Transfer
   *
   * <p>Funds in the main account, trading account and margin account of a Master Account can be
   * transferred to the main account, trading account, futures account and margin account of its
   * Sub-Account. The futures account of both the Master Account and Sub-Account can only accept
   * funds transferred in from the main account, trading account and margin account and cannot
   * transfer out to these accounts.
   *
   * <p>Extra API Info:
   *
   * <ul>
   *   <li>API-DOMAIN : SPOT
   *   <li>API-CHANNEL : PRIVATE
   *   <li>API-PERMISSION : SPOT
   *   <li>API-RATE-LIMIT-POOL : MANAGEMENT
   *   <li>API-RATE-LIMIT-WEIGHT : 30
   * </ul>
   *
   * @see <a href="https://www.kucoin.com/docs-new/api-3470301">docs</a>
   */
  @Deprecated
  SubAccountTransferResp subAccountTransfer(SubAccountTransferReq req);

  /**
   * Internal Transfer
   *
   * <p>This API endpoint can be used to transfer funds between accounts internally. Users can
   * transfer funds between their accounts free of charge.
   *
   * <p>Extra API Info:
   *
   * <ul>
   *   <li>API-DOMAIN : SPOT
   *   <li>API-CHANNEL : PRIVATE
   *   <li>API-PERMISSION : SPOT
   *   <li>API-RATE-LIMIT-POOL : MANAGEMENT
   *   <li>API-RATE-LIMIT-WEIGHT : 10
   * </ul>
   *
   * @see <a href="https://www.kucoin.com/docs-new/api-3470302">docs</a>
   */
  @Deprecated
  InnerTransferResp innerTransfer(InnerTransferReq req);

  /**
   * Get Futures Account Transfer Out Ledger
   *
   * <p>Futures account transfer out ledgers can be obtained at this endpoint.
   *
   * <p>Extra API Info:
   *
   * <ul>
   *   <li>API-DOMAIN : FUTURES
   *   <li>API-CHANNEL : PRIVATE
   *   <li>API-PERMISSION : GENERAL
   *   <li>API-RATE-LIMIT-POOL : MANAGEMENT
   *   <li>API-RATE-LIMIT-WEIGHT : 20
   * </ul>
   *
   * @see <a href="https://www.kucoin.com/docs-new/api-3470307">docs</a>
   */
  @Deprecated
  GetFuturesAccountTransferOutLedgerResp getFuturesAccountTransferOutLedger(
      GetFuturesAccountTransferOutLedgerReq req);

  /**
   * Futures Account Transfer Out
   *
   * <p>The amount to be transferred will be deducted from the KuCoin Futures Account. Please ensure
   * that you have sufficient funds in your KuCoin Futures Account, or the transfer will fail.
   *
   * <p>Extra API Info:
   *
   * <ul>
   *   <li>API-DOMAIN : FUTURES
   *   <li>API-CHANNEL : PRIVATE
   *   <li>API-PERMISSION : FUTURES
   *   <li>API-RATE-LIMIT-POOL : MANAGEMENT
   *   <li>API-RATE-LIMIT-WEIGHT : 20
   * </ul>
   *
   * @see <a href="https://www.kucoin.com/docs-new/api-3470303">docs</a>
   */
  @Deprecated
  FuturesAccountTransferOutResp futuresAccountTransferOut(FuturesAccountTransferOutReq req);

  /**
   * Futures Account Transfer In
   *
   * <p>The amount to be transferred will be deducted from the payAccount. Please ensure that you
   * have sufficient funds in your payAccount account, or the transfer will fail.
   *
   * <p>Extra API Info:
   *
   * <ul>
   *   <li>API-DOMAIN : FUTURES
   *   <li>API-CHANNEL : PRIVATE
   *   <li>API-PERMISSION : FUTURES
   *   <li>API-RATE-LIMIT-POOL : MANAGEMENT
   *   <li>API-RATE-LIMIT-WEIGHT : 20
   * </ul>
   *
   * @see <a href="https://www.kucoin.com/docs-new/api-3470304">docs</a>
   */
  @Deprecated
  FuturesAccountTransferInResp futuresAccountTransferIn(FuturesAccountTransferInReq req);
}
