// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.transfer;

import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class TransferApiImpl implements TransferApi {
  private final Transport transport;

  public TransferApiImpl(Transport transport) {
    this.transport = transport;
  }

  public GetTransferQuotasResp getTransferQuotas(GetTransferQuotasReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/accounts/transferable",
        req,
        GetTransferQuotasResp.class,
        false);
  }

  public FlexTransferResp flexTransfer(FlexTransferReq req) {
    return this.transport.call(
        "spot",
        false,
        "POST",
        "/api/v3/accounts/universal-transfer",
        req,
        FlexTransferResp.class,
        false);
  }

  public SubAccountTransferResp subAccountTransfer(SubAccountTransferReq req) {
    return this.transport.call(
        "spot",
        false,
        "POST",
        "/api/v2/accounts/sub-transfer",
        req,
        SubAccountTransferResp.class,
        false);
  }

  public InnerTransferResp innerTransfer(InnerTransferReq req) {
    return this.transport.call(
        "spot",
        false,
        "POST",
        "/api/v2/accounts/inner-transfer",
        req,
        InnerTransferResp.class,
        false);
  }

  public GetFuturesAccountTransferOutLedgerResp getFuturesAccountTransferOutLedger(
      GetFuturesAccountTransferOutLedgerReq req) {
    return this.transport.call(
        "futures",
        false,
        "GET",
        "/api/v1/transfer-list",
        req,
        GetFuturesAccountTransferOutLedgerResp.class,
        false);
  }

  public FuturesAccountTransferOutResp futuresAccountTransferOut(FuturesAccountTransferOutReq req) {
    return this.transport.call(
        "futures",
        false,
        "POST",
        "/api/v3/transfer-out",
        req,
        FuturesAccountTransferOutResp.class,
        false);
  }

  public FuturesAccountTransferInResp futuresAccountTransferIn(FuturesAccountTransferInReq req) {
    return this.transport.call(
        "futures",
        false,
        "POST",
        "/api/v1/transfer-in",
        req,
        FuturesAccountTransferInResp.class,
        false);
  }
}
