<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Account\Deposit;

use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Serializer;
use KuCoin\UniversalSDK\Internal\Interfaces\Serializable;

class AddDepositAddressV3Req implements Serializable
{
    /**
     * @var string[] $pathVarMapping
     * @Exclude()
     */
    public static $pathVarMapping = [];

    public function pathVarMapping()
    {
        return self::$pathVarMapping;
    }
    /**
     * currency
     * @var string $currency
     * @Type("string")
     * @SerializedName("currency")
     */
    public $currency;
    /**
     * The currency chainId, e.g. the available values for USDT are OMNI, ERC20, and TRC20; default is ERC20. The available values for BTC are Native, Segwit, TRC20; the parameters are bech32, btc, trx; default is Native.
     * @var string $chain
     * @Type("string")
     * @SerializedName("chain")
     */
    public $chain = "eth";
    /**
     * Deposit account type: MAIN (funding account), TRADE (spot trading account); the default is MAIN
     * - 'main' : Funding account
     * - 'trade' : Spot account
     * @var string|null $to
     * @Type("string")
     * @SerializedName("to")
     */
    public $to = "main";
    /**
     * Deposit amount. This parameter is only used when applying for invoices on the Lightning Network. This parameter is invalid if it is not passed through the Lightning Network.
     * @var string|null $amount
     * @Type("string")
     * @SerializedName("amount")
     */
    public $amount;

    private function __construct() {}

    /**
     * @param Serializer $serializer
     * @return string
     */
    public function jsonSerialize($serializer)
    {
        return $serializer->serialize($this, "json");
    }

    /**
     * @param string $json
     * @param Serializer $serializer
     * @return self
     */
    public static function jsonDeserialize($json, $serializer)
    {
        if ($json === null) {
            return new self();
        }
        return $serializer->deserialize(
            $json,
            AddDepositAddressV3Req::class,
            "json"
        );
    }
    /**
     * Creates a new instance of the `AddDepositAddressV3Req` class.
     * The builder pattern allows step-by-step construction of a `AddDepositAddressV3Req` object.
     * @return AddDepositAddressV3ReqBuilder
     */
    public static function builder()
    {
        return new AddDepositAddressV3ReqBuilder(new self());
    }

    /**
     * Creates a new instance of the `AddDepositAddressV3Req` class with the given data.
     * Ensure that the keys in data match the target field names in the documentation,
     * rather than the variable names in the class.
     * @return self
     */
    public static function create(array $data)
    {
        $obj = new self();
        foreach ($data as $key => $value) {
            if (property_exists($obj, $key)) {
                $obj->$key = $value;
            }
        }
        return $obj;
    }
}

class AddDepositAddressV3ReqBuilder
{
    /**
     * @var AddDepositAddressV3Req $obj
     */
    private $obj;

    public function __construct(AddDepositAddressV3Req $obj)
    {
        $this->obj = $obj;
    }
    /**
     * currency
     * @param string $value
     * @return self
     */
    public function setCurrency($value)
    {
        $this->obj->currency = $value;
        return $this;
    }

    /**
     * The currency chainId, e.g. the available values for USDT are OMNI, ERC20, and TRC20; default is ERC20. The available values for BTC are Native, Segwit, TRC20; the parameters are bech32, btc, trx; default is Native.
     * @param string $value
     * @return self
     */
    public function setChain($value)
    {
        $this->obj->chain = $value;
        return $this;
    }

    /**
     * Deposit account type: MAIN (funding account), TRADE (spot trading account); the default is MAIN
     * - 'main' : Funding account
     * - 'trade' : Spot account
     * @param string $value
     * @return self
     */
    public function setTo($value)
    {
        $this->obj->to = $value;
        return $this;
    }

    /**
     * Deposit amount. This parameter is only used when applying for invoices on the Lightning Network. This parameter is invalid if it is not passed through the Lightning Network.
     * @param string $value
     * @return self
     */
    public function setAmount($value)
    {
        $this->obj->amount = $value;
        return $this;
    }

    /**
     * Get the final object.
     * @return AddDepositAddressV3Req
     */
    public function build()
    {
        return $this->obj;
    }
}
