<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Account\Deposit;

use JMS\Serializer\Annotation\Exclude;
use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Serializer;
use KuCoin\UniversalSDK\Internal\Interfaces\Request;

class GetDepositAddressV3Req implements Request
{
    /**
     * @var string[] $pathVarMapping
     * @Exclude()
     */
    public static $pathVarMapping = [];

    public function pathVarMapping()
    {
        return self::$pathVarMapping;
    }
    /**
     * currency
     * @var string|null $currency
     * @Type("string")
     * @SerializedName("currency")
     */
    public $currency;
    /**
     * Deposit amount. This parameter is only used when applying for invoices on the Lightning Network. This parameter is invalid if it is not passed through the Lightning Network.
     * @var string|null $amount
     * @Type("string")
     * @SerializedName("amount")
     */
    public $amount;
    /**
     * The chain Id of currency.
     * @var string|null $chain
     * @Type("string")
     * @SerializedName("chain")
     */
    public $chain;

    private function __construct() {}

    /**
     * @param Serializer $serializer
     * @return string
     */
    public function jsonSerialize($serializer)
    {
        return $serializer->serialize($this, "json");
    }

    /**
     * @param string $json
     * @param Serializer $serializer
     * @return self
     */
    public static function jsonDeserialize($json, $serializer)
    {
        return $serializer->deserialize(
            $json,
            GetDepositAddressV3Req::class,
            "json"
        );
    }
    /**
     * Creates a new instance of the `GetDepositAddressV3Req` class.
     * The builder pattern allows step-by-step construction of a `GetDepositAddressV3Req` object.
     * @return GetDepositAddressV3ReqBuilder
     */
    public static function builder()
    {
        return new GetDepositAddressV3ReqBuilder(new self());
    }

    /**
     * Creates a new instance of the `GetDepositAddressV3Req` class with the given data.
     * Ensure that the keys in data match the target field names in the documentation,
     * rather than the variable names in the class.
     * @return self
     */
    public static function create(array $data)
    {
        $obj = new self();
        foreach ($data as $key => $value) {
            if (property_exists($obj, $key)) {
                $obj->$key = $value;
            }
        }
        return $obj;
    }
}

class GetDepositAddressV3ReqBuilder
{
    /**
     * @var GetDepositAddressV3Req $obj
     */
    private $obj;

    public function __construct(GetDepositAddressV3Req $obj)
    {
        $this->obj = $obj;
    }
    /**
     * currency
     * @param string $value
     * @return self
     */
    public function setCurrency($value)
    {
        $this->obj->currency = $value;
        return $this;
    }

    /**
     * Deposit amount. This parameter is only used when applying for invoices on the Lightning Network. This parameter is invalid if it is not passed through the Lightning Network.
     * @param string $value
     * @return self
     */
    public function setAmount($value)
    {
        $this->obj->amount = $value;
        return $this;
    }

    /**
     * The chain Id of currency.
     * @param string $value
     * @return self
     */
    public function setChain($value)
    {
        $this->obj->chain = $value;
        return $this;
    }

    /**
     * Get the final object.
     * @return GetDepositAddressV3Req
     */
    public function build()
    {
        return $this->obj;
    }
}
