// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.deposit;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetDepositAddressV3Req implements Request {
  /** currency */
  @JsonProperty("currency")
  private String currency;

  /**
   * Deposit amount. This parameter is only used when applying for invoices on the Lightning
   * Network. This parameter is invalid if it is not passed through the Lightning Network.
   */
  @JsonProperty("amount")
  private String amount;

  /** The chain Id of currency. */
  @JsonProperty("chain")
  private String chain;
}
