<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Service;

use KuCoin\UniversalSDK\Generate\Affiliate\Affiliate\AffiliateAPI;
use KuCoin\UniversalSDK\Generate\Affiliate\Affiliate\AffiliateAPIImpl;

interface AffiliateService
{
    public function getAffiliateApi(): AffiliateAPI;
}
