<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Service;

use KuCoin\UniversalSDK\Generate\Earn\Earn\EarnAPI;

interface EarnService
{
    public function getEarnApi(): EarnAPI;
}
