<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Service;

use KuCoin\UniversalSDK\Generate\Futures\Fundingfees\FundingFeesApi;
use KuCoin\UniversalSDK\Generate\Futures\Market\MarketApi;
use KuCoin\UniversalSDK\Generate\Futures\Order\OrderApi;
use KuCoin\UniversalSDK\Generate\Futures\Positions\PositionsApi;
use KuCoin\UniversalSDK\Generate\Futures\Fundingfees\FundingFeesApiImpl;
use KuCoin\UniversalSDK\Generate\Futures\Market\MarketApiImpl;
use KuCoin\UniversalSDK\Generate\Futures\Order\OrderApiImpl;
use KuCoin\UniversalSDK\Generate\Futures\Positions\PositionsApiImpl;

class FuturesServiceImpl implements FuturesService
{
    private $transport;
    private $order;
    private $positions;
    private $fundingFees;
    private $market;

    public function __construct($transport)
    {
        $this->transport = $transport;
        $this->order = new OrderApiImpl($transport);
        $this->positions = new PositionsApiImpl($transport);
        $this->fundingFees = new FundingFeesApiImpl($transport);
        $this->market = new MarketApiImpl($transport);
    }

    public function getOrderApi(): OrderApi
    {
        return $this->order;
    }

    public function getPositionsApi(): PositionsApi
    {
        return $this->positions;
    }

    public function getFundingFeesApi(): FundingFeesApi
    {
        return $this->fundingFees;
    }

    public function getMarketApi(): MarketApi
    {
        return $this->market;
    }
}
