<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Service;

use KuCoin\UniversalSDK\Generate\Margin\Credit\CreditApi;
use KuCoin\UniversalSDK\Generate\Margin\Debit\DebitApi;
use KuCoin\UniversalSDK\Generate\Margin\Market\MarketApi;
use KuCoin\UniversalSDK\Generate\Margin\Order\OrderApi;
use KuCoin\UniversalSDK\Generate\Margin\Risklimit\RiskLimitApi;

interface MarginService
{
    public function getOrderApi(): OrderApi;

    public function getDebitApi(): DebitApi;

    public function getCreditApi(): CreditApi;

    public function getMarketApi(): MarketApi;

    public function getRiskLimitApi(): RiskLimitApi;
}
