// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package subaccount

// GetSpotSubAccountDetailReq struct for GetSpotSubAccountDetailReq
type GetSpotSubAccountDetailReq struct {
	// the userID of a sub-account.
	SubUserId *string `json:"subUserId,omitempty" path:"subUserId" url:"-"`
	// False: Do not display currencies with 0 assets; True: display all currencies
	IncludeBaseAmount *bool `json:"includeBaseAmount,omitempty" url:"includeBaseAmount,omitempty"`
	// Specify the currency used to convert assets
	BaseCurrency *string `json:"baseCurrency,omitempty" url:"baseCurrency,omitempty"`
	// The currency balance specified must be greater than or equal to the amount
	BaseAmount *string `json:"baseAmount,omitempty" url:"baseAmount,omitempty"`
}

// NewGetSpotSubAccountDetailReq instantiates a new GetSpotSubAccountDetailReq object
// This constructor will assign default values to properties that have it defined
func NewGetSpotSubAccountDetailReq() *GetSpotSubAccountDetailReq {
	this := GetSpotSubAccountDetailReq{}
	var includeBaseAmount bool = false
	this.IncludeBaseAmount = &includeBaseAmount
	return &this
}

// NewGetSpotSubAccountDetailReqWithDefaults instantiates a new GetSpotSubAccountDetailReq object
// This constructor will only assign default values to properties that have it defined,
func NewGetSpotSubAccountDetailReqWithDefaults() *GetSpotSubAccountDetailReq {
	this := GetSpotSubAccountDetailReq{}
	var includeBaseAmount bool = false
	this.IncludeBaseAmount = &includeBaseAmount
	return &this
}

func (o *GetSpotSubAccountDetailReq) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["subUserId"] = o.SubUserId
	toSerialize["includeBaseAmount"] = o.IncludeBaseAmount
	toSerialize["baseCurrency"] = o.BaseCurrency
	toSerialize["baseAmount"] = o.BaseAmount
	return toSerialize
}

type GetSpotSubAccountDetailReqBuilder struct {
	obj *GetSpotSubAccountDetailReq
}

func NewGetSpotSubAccountDetailReqBuilder() *GetSpotSubAccountDetailReqBuilder {
	return &GetSpotSubAccountDetailReqBuilder{obj: NewGetSpotSubAccountDetailReqWithDefaults()}
}

// the userID of a sub-account.
func (builder *GetSpotSubAccountDetailReqBuilder) SetSubUserId(value string) *GetSpotSubAccountDetailReqBuilder {
	builder.obj.SubUserId = &value
	return builder
}

// False: Do not display currencies with 0 assets; True: display all currencies
func (builder *GetSpotSubAccountDetailReqBuilder) SetIncludeBaseAmount(value bool) *GetSpotSubAccountDetailReqBuilder {
	builder.obj.IncludeBaseAmount = &value
	return builder
}

// Specify the currency used to convert assets
func (builder *GetSpotSubAccountDetailReqBuilder) SetBaseCurrency(value string) *GetSpotSubAccountDetailReqBuilder {
	builder.obj.BaseCurrency = &value
	return builder
}

// The currency balance specified must be greater than or equal to the amount
func (builder *GetSpotSubAccountDetailReqBuilder) SetBaseAmount(value string) *GetSpotSubAccountDetailReqBuilder {
	builder.obj.BaseAmount = &value
	return builder
}

func (builder *GetSpotSubAccountDetailReqBuilder) Build() *GetSpotSubAccountDetailReq {
	return builder.obj
}
