// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package subaccount

// GetFuturesSubAccountListV2Summary struct for GetFuturesSubAccountListV2Summary
type GetFuturesSubAccountListV2Summary struct {
	// Total Account Equity
	AccountEquityTotal float64 `json:"accountEquityTotal,omitempty"`
	// Total unrealizedPNL
	UnrealisedPNLTotal float64 `json:"unrealisedPNLTotal,omitempty"`
	// Total Margin Balance
	MarginBalanceTotal float64 `json:"marginBalanceTotal,omitempty"`
	// Total Position margin
	PositionMarginTotal float64 `json:"positionMarginTotal,omitempty"`
	OrderMarginTotal    float64 `json:"orderMarginTotal,omitempty"`
	// Total frozen funds for withdrawal and out-transfer
	FrozenFundsTotal float64 `json:"frozenFundsTotal,omitempty"`
	// Total available balance
	AvailableBalanceTotal float64 `json:"availableBalanceTotal,omitempty"`
	Currency              string  `json:"currency,omitempty"`
}

// NewGetFuturesSubAccountListV2Summary instantiates a new GetFuturesSubAccountListV2Summary object
// This constructor will assign default values to properties that have it defined
func NewGetFuturesSubAccountListV2Summary(accountEquityTotal float64, unrealisedPNLTotal float64, marginBalanceTotal float64, positionMarginTotal float64, orderMarginTotal float64, frozenFundsTotal float64, availableBalanceTotal float64, currency string) *GetFuturesSubAccountListV2Summary {
	this := GetFuturesSubAccountListV2Summary{}
	this.AccountEquityTotal = accountEquityTotal
	this.UnrealisedPNLTotal = unrealisedPNLTotal
	this.MarginBalanceTotal = marginBalanceTotal
	this.PositionMarginTotal = positionMarginTotal
	this.OrderMarginTotal = orderMarginTotal
	this.FrozenFundsTotal = frozenFundsTotal
	this.AvailableBalanceTotal = availableBalanceTotal
	this.Currency = currency
	return &this
}

// NewGetFuturesSubAccountListV2SummaryWithDefaults instantiates a new GetFuturesSubAccountListV2Summary object
// This constructor will only assign default values to properties that have it defined,
func NewGetFuturesSubAccountListV2SummaryWithDefaults() *GetFuturesSubAccountListV2Summary {
	this := GetFuturesSubAccountListV2Summary{}
	return &this
}

func (o *GetFuturesSubAccountListV2Summary) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["accountEquityTotal"] = o.AccountEquityTotal
	toSerialize["unrealisedPNLTotal"] = o.UnrealisedPNLTotal
	toSerialize["marginBalanceTotal"] = o.MarginBalanceTotal
	toSerialize["positionMarginTotal"] = o.PositionMarginTotal
	toSerialize["orderMarginTotal"] = o.OrderMarginTotal
	toSerialize["frozenFundsTotal"] = o.FrozenFundsTotal
	toSerialize["availableBalanceTotal"] = o.AvailableBalanceTotal
	toSerialize["currency"] = o.Currency
	return toSerialize
}
