// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.fee;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetBasicFeeResp implements Response<GetBasicFeeResp, RestResponse<GetBasicFeeResp>> {
  /** Base taker fee rate */
  @JsonProperty("takerFeeRate")
  private String takerFeeRate;

  /** Base maker fee rate */
  @JsonProperty("makerFeeRate")
  private String makerFeeRate;

  /** common response */
  @JsonIgnore private RestResponse<GetBasicFeeResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<GetBasicFeeResp> response) {
    this.commonResponse = response;
  }
}
