// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.fee;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetFuturesActualFeeResp
    implements Response<GetFuturesActualFeeResp, RestResponse<GetFuturesActualFeeResp>> {
  /**
   * The unique identity of the trading pair; will not change even if the trading pair is renamed
   */
  @JsonProperty("symbol")
  private String symbol;

  /** Actual taker fee rate of the trading pair */
  @JsonProperty("takerFeeRate")
  private String takerFeeRate;

  /** Actual maker fee rate of the trading pair */
  @JsonProperty("makerFeeRate")
  private String makerFeeRate;

  /** common response */
  @JsonIgnore private RestResponse<GetFuturesActualFeeResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<GetFuturesActualFeeResp> response) {
    this.commonResponse = response;
  }
}
