// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.market;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class Get24hrStatsResp
    implements Response<Get24hrStatsResp, RestResponse<Get24hrStatsResp>> {
  /** timestamp */
  @JsonProperty("time")
  private Long time;

  /** Symbol */
  @JsonProperty("symbol")
  private String symbol;

  /** Best bid price */
  @JsonProperty("buy")
  private String buy;

  /** Best ask price */
  @JsonProperty("sell")
  private String sell;

  /** 24h change rate */
  @JsonProperty("changeRate")
  private String changeRate;

  /** 24h change price */
  @JsonProperty("changePrice")
  private String changePrice;

  /** Highest price in 24h */
  @JsonProperty("high")
  private String high;

  /** Lowest price in 24h */
  @JsonProperty("low")
  private String low;

  /** 24h volume, executed based on base currency */
  @JsonProperty("vol")
  private String vol;

  /** 24h traded amount */
  @JsonProperty("volValue")
  private String volValue;

  /** Last traded price */
  @JsonProperty("last")
  private String last;

  /** Average trading price in the last 24 hours */
  @JsonProperty("averagePrice")
  private String averagePrice;

  /** Basic Taker Fee */
  @JsonProperty("takerFeeRate")
  private String takerFeeRate;

  /** Basic Maker Fee */
  @JsonProperty("makerFeeRate")
  private String makerFeeRate;

  /**
   * The taker fee coefficient. The actual fee needs to be multiplied by this coefficient to get the
   * final fee. Most currencies have a coefficient of 1. If set to 0, it means no fee
   */
  @JsonProperty("takerCoefficient")
  private String takerCoefficient;

  /**
   * The maker fee coefficient. The actual fee needs to be multiplied by this coefficient to get the
   * final fee. Most currencies have a coefficient of 1. If set to 0, it means no fee
   */
  @JsonProperty("makerCoefficient")
  private String makerCoefficient;

  /** common response */
  @JsonIgnore private RestResponse<Get24hrStatsResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<Get24hrStatsResp> response) {
    this.commonResponse = response;
  }
}
