// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.market;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.PathVar;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetCurrencyReq implements Request {
  /**
   * Support for querying the chain of currency, e.g. the available values for USDT are OMNI, ERC20,
   * TRC20. This only applies to multi-chain currencies; no need for single-chain currencies.
   */
  @JsonProperty("chain")
  private String chain;

  /** Path parameter, Currency */
  @JsonIgnore
  @PathVar("currency")
  @JsonProperty("currency")
  private String currency;
}
