// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.spotpublic;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.internal.interfaces.WebSocketMessageCallback;
import com.kucoin.universal.sdk.model.WsMessage;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class CallAuctionOrderbookLevel50Event
    implements Response<CallAuctionOrderbookLevel50Event,
                        WsMessage<CallAuctionOrderbookLevel50Event>> {
  /**
   * price, size
   */
  @JsonProperty("asks") private List<List<String>> asks = new ArrayList<>();
  /**
   *
   */
  @JsonProperty("bids") private List<List<String>> bids = new ArrayList<>();
  /**
   *
   */
  @JsonProperty("timestamp") private Long timestamp;
  /**
   * common response
   */
  @JsonIgnore
  private WsMessage<CallAuctionOrderbookLevel50Event> commonResponse;

  @Override
  public void
  setCommonResponse(WsMessage<CallAuctionOrderbookLevel50Event> response) {
    this.commonResponse = response;
  }

  @FunctionalInterface
  public interface Callback {
    void onEvent(String topic, String subject,
                 CallAuctionOrderbookLevel50Event data);
  }

  public static class CallbackAdapters {
    public static WebSocketMessageCallback<CallAuctionOrderbookLevel50Event>
    of(Callback callback) {
      return msg
          -> callback.onEvent(msg.getTopic(), msg.getSubject(), msg.getData());
    }
  }
}
