// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.spot.spotpublic;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.internal.interfaces.WebSocketMessageCallback;
import com.kucoin.universal.sdk.model.WsMessage;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrderbookIncrementEvent implements Response<OrderbookIncrementEvent, WsMessage> {
  /** */
  @JsonProperty("changes")
  private OrderbookIncrementChanges changes;

  /** */
  @JsonProperty("sequenceEnd")
  private Long sequenceEnd;

  /** */
  @JsonProperty("sequenceStart")
  private Long sequenceStart;

  /** */
  @JsonProperty("symbol")
  private String symbol;

  /** milliseconds */
  @JsonProperty("time")
  private Long time;

  /** common response */
  @JsonIgnore private WsMessage commonResponse;

  @Override
  public void setCommonResponse(WsMessage response) {
    this.commonResponse = response;
  }

  @FunctionalInterface
  public interface Callback {
    void onEvent(String topic, String subject, OrderbookIncrementEvent data);
  }

  public static class CallbackAdapters {
    public static WebSocketMessageCallback of(Callback callback) {
      return (msg, objectMapper) ->
          callback.onEvent(
              msg.getTopic(),
              msg.getSubject(),
              objectMapper.convertValue(msg.getData(), OrderbookIncrementEvent.class));
    }
  }
}
