
.PHONY: build
build:
	echo "stub"

.PHONY: auto-test
auto-test: build
	echo "done"

.PHONY: before-release-test
before-release-test: build
	echo "done"

.PHONY: after-release-test
after-release-test: build
	echo "done"

.PHONY: run-forever-test
run-forever-test: build
	echo "done"

.PHONY: reconnect-test
reconnect-test: build
	echo "done"