// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.margin.debit;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetInterestHistoryResp
    implements Response<GetInterestHistoryResp, RestResponse<GetInterestHistoryResp>> {
  /** */
  @JsonProperty("timestamp")
  private Long timestamp;

  /** current page */
  @JsonProperty("currentPage")
  private Integer currentPage;

  /** page size */
  @JsonProperty("pageSize")
  private Integer pageSize;

  /** total number */
  @JsonProperty("totalNum")
  private Integer totalNum;

  /** total pages */
  @JsonProperty("totalPage")
  private Integer totalPage;

  /** */
  @JsonProperty("items")
  private List<GetInterestHistoryItems> items = new ArrayList<>();

  /** common response */
  @JsonIgnore private RestResponse<GetInterestHistoryResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<GetInterestHistoryResp> response) {
    this.commonResponse = response;
  }
}
