<?php
// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

namespace KuCoin\UniversalSDK\Generate\Account\Transfer;

interface TransferApi
{
    /**
     * Get Transfer Quotas
     *
     * This endpoint returns the transferable balance of a specified account.
     * @see: https://www.kucoin.com/docs-new/api-3470148
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | GENERAL    |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 20         |
     * +-----------------------+------------+
     */
    public function getTransferQuotas(
        GetTransferQuotasReq $req
    ): GetTransferQuotasResp;

    /**
     * Flex Transfer
     *
     * This interface can be used for transfers between master- and sub-accounts and transfers
     * @see: https://www.kucoin.com/docs-new/api-3470147
     *
     * +-----------------------+---------------+
     * | Extra API Info        | Value         |
     * +-----------------------+---------------+
     * | API-DOMAIN            | SPOT          |
     * | API-CHANNEL           | PRIVATE       |
     * | API-PERMISSION        | FLEXTRANSFERS |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT    |
     * | API-RATE-LIMIT-WEIGHT | 4             |
     * +-----------------------+---------------+
     */
    public function flexTransfer(FlexTransferReq $req): FlexTransferResp;

    /**
     * Sub-account Transfer
     *
     * Funds in the main account, trading account and margin account of a Master Account can be transferred to the main account, trading account, futures account and margin account of its Sub-Account. The futures account of both the Master Account and Sub-Account can only accept funds transferred in from the main account, trading account and margin account and cannot transfer out to these accounts.
     * @deprecated
     * @see: https://www.kucoin.com/docs-new/api-3470301
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | SPOT       |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 30         |
     * +-----------------------+------------+
     */
    public function subAccountTransfer(
        SubAccountTransferReq $req
    ): SubAccountTransferResp;

    /**
     * Internal Transfer
     *
     * This API endpoint can be used to transfer funds between accounts internally. Users can transfer funds between their accounts free of charge.
     * @deprecated
     * @see: https://www.kucoin.com/docs-new/api-3470302
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | SPOT       |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | SPOT       |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 10         |
     * +-----------------------+------------+
     */
    public function innerTransfer(InnerTransferReq $req): InnerTransferResp;

    /**
     * Get Futures Account Transfer Out Ledger
     *
     * Futures account transfer out ledgers can be obtained at this endpoint.
     * @deprecated
     * @see: https://www.kucoin.com/docs-new/api-3470307
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | FUTURES    |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | GENERAL    |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 20         |
     * +-----------------------+------------+
     */
    public function getFuturesAccountTransferOutLedger(
        GetFuturesAccountTransferOutLedgerReq $req
    ): GetFuturesAccountTransferOutLedgerResp;

    /**
     * Futures Account Transfer Out
     *
     * The amount to be transferred will be deducted from the KuCoin Futures Account. Please ensure that you have sufficient funds in your KuCoin Futures Account, or the transfer will fail.
     * @deprecated
     * @see: https://www.kucoin.com/docs-new/api-3470303
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | FUTURES    |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | FUTURES    |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 20         |
     * +-----------------------+------------+
     */
    public function futuresAccountTransferOut(
        FuturesAccountTransferOutReq $req
    ): FuturesAccountTransferOutResp;

    /**
     * Futures Account Transfer In
     *
     * The amount to be transferred will be deducted from the payAccount. Please ensure that you have sufficient funds in your payAccount account, or the transfer will fail.
     * @deprecated
     * @see: https://www.kucoin.com/docs-new/api-3470304
     *
     * +-----------------------+------------+
     * | Extra API Info        | Value      |
     * +-----------------------+------------+
     * | API-DOMAIN            | FUTURES    |
     * | API-CHANNEL           | PRIVATE    |
     * | API-PERMISSION        | FUTURES    |
     * | API-RATE-LIMIT-POOL   | MANAGEMENT |
     * | API-RATE-LIMIT-WEIGHT | 20         |
     * +-----------------------+------------+
     */
    public function futuresAccountTransferIn(
        FuturesAccountTransferInReq $req
    ): FuturesAccountTransferInResp;
}
