// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.account;

import com.kucoin.universal.sdk.internal.interfaces.Transport;

public class AccountApiImpl implements AccountApi {
  private final Transport transport;

  public AccountApiImpl(Transport transport) {
    this.transport = transport;
  }

  public GetAccountInfoResp getAccountInfo() {
    return this.transport.call(
        "spot", false, "GET", "/api/v2/user-info", null, GetAccountInfoResp.class, false);
  }

  public GetApikeyInfoResp getApikeyInfo() {
    return this.transport.call(
        "spot", false, "GET", "/api/v1/user/api-key", null, GetApikeyInfoResp.class, false);
  }

  public GetSpotAccountTypeResp getSpotAccountType() {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/hf/accounts/opened",
        null,
        GetSpotAccountTypeResp.class,
        false);
  }

  public GetSpotAccountListResp getSpotAccountList(GetSpotAccountListReq req) {
    return this.transport.call(
        "spot", false, "GET", "/api/v1/accounts", req, GetSpotAccountListResp.class, false);
  }

  public GetSpotAccountDetailResp getSpotAccountDetail(GetSpotAccountDetailReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/accounts/{accountId}",
        req,
        GetSpotAccountDetailResp.class,
        false);
  }

  public GetCrossMarginAccountResp getCrossMarginAccount(GetCrossMarginAccountReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v3/margin/accounts",
        req,
        GetCrossMarginAccountResp.class,
        false);
  }

  public GetIsolatedMarginAccountResp getIsolatedMarginAccount(GetIsolatedMarginAccountReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v3/isolated/accounts",
        req,
        GetIsolatedMarginAccountResp.class,
        false);
  }

  public GetFuturesAccountResp getFuturesAccount(GetFuturesAccountReq req) {
    return this.transport.call(
        "futures",
        false,
        "GET",
        "/api/v1/account-overview",
        req,
        GetFuturesAccountResp.class,
        false);
  }

  public GetSpotLedgerResp getSpotLedger(GetSpotLedgerReq req) {
    return this.transport.call(
        "spot", false, "GET", "/api/v1/accounts/ledgers", req, GetSpotLedgerResp.class, false);
  }

  public GetSpotHFLedgerResp getSpotHFLedger(GetSpotHFLedgerReq req) {
    return this.transport.call(
        "spot", false, "GET", "/api/v1/hf/accounts/ledgers", req, GetSpotHFLedgerResp.class, false);
  }

  public GetMarginHFLedgerResp getMarginHFLedger(GetMarginHFLedgerReq req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v3/hf/margin/account/ledgers",
        req,
        GetMarginHFLedgerResp.class,
        false);
  }

  public GetFuturesLedgerResp getFuturesLedger(GetFuturesLedgerReq req) {
    return this.transport.call(
        "futures",
        false,
        "GET",
        "/api/v1/transaction-history",
        req,
        GetFuturesLedgerResp.class,
        false);
  }

  public GetMarginAccountDetailResp getMarginAccountDetail() {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/margin/account",
        null,
        GetMarginAccountDetailResp.class,
        false);
  }

  public GetIsolatedMarginAccountListV1Resp getIsolatedMarginAccountListV1(
      GetIsolatedMarginAccountListV1Req req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/isolated/accounts",
        req,
        GetIsolatedMarginAccountListV1Resp.class,
        false);
  }

  public GetIsolatedMarginAccountDetailV1Resp getIsolatedMarginAccountDetailV1(
      GetIsolatedMarginAccountDetailV1Req req) {
    return this.transport.call(
        "spot",
        false,
        "GET",
        "/api/v1/isolated/account/{symbol}",
        req,
        GetIsolatedMarginAccountDetailV1Resp.class,
        false);
  }
}
