// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetAccountInfoResp
    implements Response<GetAccountInfoResp, RestResponse<GetAccountInfoResp>> {
  /** User VIP level */
  @JsonProperty("level")
  private Integer level;

  /** Number of sub-accounts */
  @JsonProperty("subQuantity")
  private Integer subQuantity;

  /** Number of sub-accounts with spot trading permissions enabled */
  @JsonProperty("spotSubQuantity")
  private Integer spotSubQuantity;

  /** Number of sub-accounts with margin trading permissions enabled */
  @JsonProperty("marginSubQuantity")
  private Integer marginSubQuantity;

  /** Number of sub-accounts with futures trading permissions enabled */
  @JsonProperty("futuresSubQuantity")
  private Integer futuresSubQuantity;

  /** Number of sub-accounts with option trading permissions enabled */
  @JsonProperty("optionSubQuantity")
  private Integer optionSubQuantity;

  /** Max. number of sub-accounts = maxDefaultSubQuantity + maxSpotSubQuantity */
  @JsonProperty("maxSubQuantity")
  private Integer maxSubQuantity;

  /** Max. number of default open sub-accounts (according to VIP level) */
  @JsonProperty("maxDefaultSubQuantity")
  private Integer maxDefaultSubQuantity;

  /** Max. number of sub-accounts with additional spot trading permissions */
  @JsonProperty("maxSpotSubQuantity")
  private Integer maxSpotSubQuantity;

  /** Max. number of sub-accounts with additional margin trading permissions */
  @JsonProperty("maxMarginSubQuantity")
  private Integer maxMarginSubQuantity;

  /** Max. number of sub-accounts with additional futures trading permissions */
  @JsonProperty("maxFuturesSubQuantity")
  private Integer maxFuturesSubQuantity;

  /** Max. number of sub-accounts with additional option trading permissions */
  @JsonProperty("maxOptionSubQuantity")
  private Integer maxOptionSubQuantity;

  /** common response */
  @JsonIgnore private RestResponse<GetAccountInfoResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<GetAccountInfoResp> response) {
    this.commonResponse = response;
  }
}
