// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.account;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetApikeyInfoResp
    implements Response<GetApikeyInfoResp, RestResponse<GetApikeyInfoResp>> {
  /** Remarks */
  @JsonProperty("remark")
  private String remark;

  /** Apikey */
  @JsonProperty("apiKey")
  private String apiKey;

  /** API Version */
  @JsonProperty("apiVersion")
  private Integer apiVersion;

  /**
   * [Permissions](https://www.kucoin.com/docs-new/doc-338144), possible values: General, Spot,
   * Margin, Futures, InnerTransfer, Transfer, Earn
   */
  @JsonProperty("permission")
  private String permission;

  /** IP whitelist */
  @JsonProperty("ipWhitelist")
  private String ipWhitelist;

  /** Apikey create time */
  @JsonProperty("createdAt")
  private Long createdAt;

  /** Account UID */
  @JsonProperty("uid")
  private Integer uid;

  /** Whether it is the master account. */
  @JsonProperty("isMaster")
  private Boolean isMaster;

  /** Sub Name, There is no such param for the master account */
  @JsonProperty("subName")
  private String subName;

  /** common response */
  @JsonIgnore private RestResponse<GetApikeyInfoResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<GetApikeyInfoResp> response) {
    this.commonResponse = response;
  }
}
