// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetFuturesLedgerDataList {
  /** Ledger time */
  @JsonProperty("time")
  private Long time;

  /** Type: RealisedPNL, Deposit, Withdrawal, TransferIn, TransferOut */
  @JsonProperty("type")
  private String type;

  /** Transaction amount */
  @JsonProperty("amount")
  private Double amount;

  /** Fee */
  @JsonProperty("fee")
  private Double fee;

  /** Account equity */
  @JsonProperty("accountEquity")
  private Double accountEquity;

  /** Status: Completed, Pending */
  @JsonProperty("status")
  private String status;

  /** Ticker symbol of the contract */
  @JsonProperty("remark")
  private String remark;

  /** Offset */
  @JsonProperty("offset")
  private Integer offset;

  /** Currency */
  @JsonProperty("currency")
  private String currency;
}
