// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.account;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Request;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetFuturesLedgerReq implements Request {
  /** Currency of transaction history, XBT or USDT */
  @JsonProperty("currency")
  private String currency;

  /**
   * Type RealizedPNL-Realized profit and loss, Deposit-Deposit, Withdrawal-withdraw,
   * Transferin-Transfer in, TransferOut-Transfer out
   */
  @JsonProperty("type")
  private String type;

  /**
   * Start offset. Generally, only the attributes of the last returned result of the previous
   * request are used, and the first page is returned by default
   */
  @JsonProperty("offset")
  private Long offset;

  /**
   * This parameter functions to judge whether the lookup is forward or not. True means “yes” and
   * False means “no”. This parameter is set as true by default.
   */
  @JsonProperty("forward")
  @Builder.Default
  private Boolean forward = true;

  /** Displayed size per page. The default size is 50 */
  @JsonProperty("maxCount")
  @Builder.Default
  private Long maxCount = 50l;

  /** Start time (milliseconds) */
  @JsonProperty("startAt")
  private Long startAt;

  /** End time (milliseconds) */
  @JsonProperty("endAt")
  private Long endAt;
}
