// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.account;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetMarginHFLedgerResp
    implements Response<GetMarginHFLedgerResp, RestResponse<GetMarginHFLedgerResp>> {
  /** */
  @JsonProperty("data")
  private List<GetMarginHFLedgerData> data = new ArrayList<>();

  /** common response */
  @JsonIgnore private RestResponse<GetMarginHFLedgerResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<GetMarginHFLedgerResp> response) {
    this.commonResponse = response;
  }

  @JsonCreator
  public static GetMarginHFLedgerResp fromJson(List<GetMarginHFLedgerData> data) {
    // original response
    GetMarginHFLedgerResp obj = new GetMarginHFLedgerResp();
    obj.data = data;
    return obj;
  }
}
