// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.affiliate.affiliate;

public interface AffiliateApi {
  /**
   * Get Account Affiliate user rebate information can be obtained at this endpoint. <a
   * href="https://www.kucoin.com/docs-new/api-3470279">docs</a>
   * +-----------------------+------------+ | Extra API Info | Value |
   * +-----------------------+------------+ | API-DOMAIN | SPOT | | API-CHANNEL | PRIVATE | |
   * API-PERMISSION | GENERAL | | API-RATE-LIMIT-POOL | MANAGEMENT | | API-RATE-LIMIT-WEIGHT | 30 |
   * +-----------------------+------------+
   */
  GetAccountResp getAccount();
}
