// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.margin.order;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.kucoin.universal.sdk.internal.interfaces.Response;
import com.kucoin.universal.sdk.model.RestResponse;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetTradeHistoryResp
    implements Response<GetTradeHistoryResp, RestResponse<GetTradeHistoryResp>> {
  /** */
  @JsonProperty("items")
  private List<GetTradeHistoryItems> items = new ArrayList<>();

  /**
   * The ID of the last set of data from the previous data batch. By default, the latest information
   * is given. lastId is used to filter data and paginate. If lastId is not entered, the default is
   * a maximum of 100 returned data items. The return results include lastId, which can be used as a
   * query parameter to look up new data from the next page.
   */
  @JsonProperty("lastId")
  private Long lastId;

  /** common response */
  @JsonIgnore private RestResponse<GetTradeHistoryResp> commonResponse;

  @Override
  public void setCommonResponse(RestResponse<GetTradeHistoryResp> response) {
    this.commonResponse = response;
  }
}
