// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.subaccount;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSpotSubAccountListV1Data {
  /** The user ID of the sub-user. */
  @JsonProperty("subUserId")
  private String subUserId;

  /** The username of the sub-user. */
  @JsonProperty("subName")
  private String subName;

  /** Funding Account */
  @JsonProperty("mainAccounts")
  private List<GetSpotSubAccountListV1DataMainAccounts> mainAccounts = new ArrayList<>();

  /** Spot Account */
  @JsonProperty("tradeAccounts")
  private List<GetSpotSubAccountListV1DataTradeAccounts> tradeAccounts = new ArrayList<>();

  /** Margin Account */
  @JsonProperty("marginAccounts")
  private List<GetSpotSubAccountListV1DataMarginAccounts> marginAccounts = new ArrayList<>();

  /** This param is deprecated and only valid for some old users */
  @JsonProperty("tradeHFAccounts")
  private List<String> tradeHFAccounts = new ArrayList<>();
}
