// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.subaccount;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSpotSubAccountListV1DataMarginAccounts {
  /** The currency of the account. */
  @JsonProperty("currency")
  private String currency;

  /** Total funds in the account. */
  @JsonProperty("balance")
  private String balance;

  /** Funds available to withdraw or trade. */
  @JsonProperty("available")
  private String available;

  /** Funds on hold (not available for use). */
  @JsonProperty("holds")
  private String holds;

  /** Calculated on this currency. */
  @JsonProperty("baseCurrency")
  private String baseCurrency;

  /** The base currency price. */
  @JsonProperty("baseCurrencyPrice")
  private String baseCurrencyPrice;

  /** The base currency amount. */
  @JsonProperty("baseAmount")
  private String baseAmount;

  /** */
  @JsonProperty("tag")
  private String tag;
}
