// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package com.kucoin.universal.sdk.generate.account.subaccount;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class GetSpotSubAccountsSummaryV1Data {
  /** */
  @JsonProperty("userId")
  private String userId;

  /** */
  @JsonProperty("uid")
  private Integer uid;

  /** */
  @JsonProperty("subName")
  private String subName;

  /** */
  @JsonProperty("type")
  private Integer type;

  /** */
  @JsonProperty("remarks")
  private String remarks;

  /** Sub-account Permission */
  @JsonProperty("access")
  private String access;
}
